### ISSUE TITLE
failed to retrieve block from DALC: given height is from the future

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#1009]
in the latest rollkit release 0.8.1 on local-celestia-devnet [v0.10.4 ](https://github.com/rollkit/local-celestia-devnet/releases/tag/v0.10.4) which is compatible with BSR (celestia-app: v0.13.3 and celestia-node: v0.10.4), throws below error. However it is not harmful, as you can see that rollkit is able to retrieve the blocks successfully. This is happening due to fast retrieve loop (100ms intervals with 10 retries). Upon the fix of celestia-node issue: https://github.com/celestiaorg/go-header/issues/32, the error should go away as retries may not be necessary. 

```7:03AM ERR failed to retrieve block from DALC daHeight=33 errors="failed to retrieve block: header: given height is from the future: networkHeight: 32, requestedHeight: 33; failed to retrieve block: header: given height is from the future: networkHeight: 32, requestedHeight: 33; failed to retrieve block: header: given height is from the future: networkHeight: 32, requestedHeight: 33; failed to retrieve block: header: given height is from the future: networkHeight: 32, requestedHeight: 33; failed to retrieve block: header: given height is from the future: networkHeight: 32, requestedHeight: 33; failed to retrieve block: header: given height is from the future: networkHeight: 32, requestedHeight: 33; failed to retrieve block: header: given height is from the future: networkHeight: 32, requestedHeight: 33; failed to retrieve block: header: given height is from the future: networkHeight: 32, requestedHeight: 33; failed to retrieve block: header: given height is from the future: networkHeight: 32, requestedHeight: 33; failed to retrieve block: header: given height is from the future: networkHeight: 32, requestedHeight: 33" module=BlockManager```

```7:04AM DBG retrieved potential blocks daHeight=33 module=BlockManager n=1```

**Comment by Manav-Aggarwal** [comment]
more recent version errors documented in https://github.com/rollkit/rollkit/issues/1030
