### ISSUE TITLE
celestia-openrpc: need data availability header of submitted height

### ISSUE THREAD

**Issue by tuxcanfly** [rollkit/rollkit#1018]
When testing the read path in replacing `go-cnc` with `celestia-openrpc`, I came across an issue where the new `share.GetSharesByNamespace` API needs to be passed the data availability header of the height at which the block was previously submitted.

Unlike before, where we could use node to scan the past blocks for data, it seems that we need to keep track of precise block heights at which rollup blocks were submitted.

This needs to be implemented in the block manager, for example, by keeping a map of `rollup block height -> da block height`.

**Comment by Wondertan** [comment]
What if you use the BlobAPI.GetAlll for this case? It returns all the blobs in the namespace for the height.

**Comment by distractedm1nd** [comment]
The way my rollup solved this pre-blobmod was doing header.GetByHeight to get the share root then doing shares.GetSharesByNamespace directly after (as one helper function)

**Comment by Wondertan** [comment]
Right, that also works.

**Comment by gupadhyaya** [comment]
would prefer `BlobAPI.GetAlll` over two calls: `GetByHeight` and `GetSharesByNamespace`

**Comment by tuxcanfly** [comment]
This would require adding `blob.Blob` type: `GetAll(height uint64, nIDs []namespace.ID)[]*blob.Blob`

**Comment by tuxcanfly** [comment]
`blob.GetAll` works, had to add `BlobAPI` to the client though.

**Comment by tuxcanfly** [comment]
`BlobAPI` works, although node logs are a bit verbose when namespace is not found:


```
2023-06-20T19:58:39.331Z        WARN    rpc
go-jsonrpc@v0.3.1/handler.go:444        error in RPC call to 'blob.GetAll':
getting blobs for nID(qX2): getter/store: failed to retrieve shares by
namespace: share: namespace not found in data blob: not found
2023-06-20T19:58:39.331Z        ERROR   rpc
go-jsonrpc@v0.3.1/handler.go:484        error and res returned  {"request":
{"jsonrpc":"2.0","id":26,"method":"blob.GetAll","params":[479,["AAAAAAAAAAAAAAAAAAAAAAAAAAAAgHEEWOgy1cg="]],"meta":{"SpanContext":"AADVpaDinnjNK1gnee1Hjd1YAT1+TE8eu2lpAgA="}},
"r.err": "getting blobs for
nID(\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffdq\u0004X\ufffd2\ufffd\ufffd):
getter/store: failed to retrieve shares by namespace: share: namespace not
found in data\nblob: not found", "res": []}
```

Closing as resolved.
