### ISSUE TITLE
Does Header verification need to check adjacent validity?

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#1032]
If we check Sequencer Signature, we might not need to check adjacent validity.

If we don't need adjacent validity, we can remove the hash checks that we are currently doing. 
If we don't need adjacent validity then we can **not** discard future headers. 

Let's say we get the Headers in the order of 1 3 2 we might be able to keep them as I think we would be currently dropping them.

This would also need appropriate testing after we decided on a scheme.

**Comment by Manav-Aggarwal** [comment]
Decided that this is needed

**Comment by gupadhyaya** [comment]
go-header already performs the adjacency check [here](https://github.com/celestiaorg/go-header/blob/main/verify.go#L36) and the implementation does not need to handle it again. @Manav-Aggarwal @nashqueue we can close this issue.
