### ISSUE TITLE
DA layer submission failure due to tx timeout

### ISSUE THREAD

**Issue by Ferret-san** [rollkit/rollkit#1036]
While sending transactions sequentially to a Rollkit sequencing node running Polaris and posting data to a local celestia devnet instance, I encountered an issue which Rollkit reports as:

```
DA layer submission failed error="Post \"http://localhost:26659/submit_pfb\": EOF" attempt=1 module=BlockManager
5:29PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=2 module=BlockManager
5:29PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=3 module=BlockManager
5:29PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=4 module=BlockManager
5:29PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=5 module=BlockManager
5:29PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=6 module=BlockManager
5:29PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=7 module=BlockManager
5:30PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=8 module=BlockManage
```

Eventually after 30 or so attempts, Rollkit uses a pending block to progress the chain, but doing so causes a height mismatch between the client (Rollkit) and the app (Polaris), which can lead to a panic.

Looking at the logs for the local celestia devnet shows that the first failed submission occurs because of `ERR Error on broadcastTxCommit err="timed out waiting for tx to be included in a block" module=rpc`, while any future attempt by Rollkit to submit the data fails because `ERR Error on broadcastTxCommit err="tx already exists in cache" module=rpc`. 

While it might be possible to change the `timeout_commit` value locally and resolve the issue, Rollkit might be better off using something like `BroadcastTxSync` or `BrodcastTxAsync`, or perhaps the change from `go-cnc` to `open-rpc` will fix this issue by allowing Rollkit to wait for the context deadline of the request more accurately, avoiding further attempts to submit a tx already in cache

**Comment by nashqueue** [comment]
We will revisit this after the move to open-rpc to see if it resolves the issue. Thank you

**Comment by Wondertan** [comment]
This won't be fixed in RPC until https://github.com/celestiaorg/celestia-app/issues/1885 is fixed

**Comment by Manav-Aggarwal** [comment]
@Ferret-san now that the move to open-rpc is done and https://github.com/celestiaorg/celestia-app/issues/1885 is fixed, is this issue resolved? cc: @Wondertan @nashqueue

**Comment by Wondertan** [comment]
We didn't integrate that feature into the node yet. @cmwater is on it

**Comment by Manav-Aggarwal** [comment]
Bumping this for revisiting @Wondertan

**Comment by tuxcanfly** [comment]
This is reproducible if blocks are full, currently tested by mocking Submit. A potential fix can be to use a context timeout so that we can retry without having to wait for tx to time out on the app.
