### ISSUE TITLE
[follow-up] We should create an issue in the go-header so that the genesis block can be handled differently, and so it does not negatively impact the block time in tests and performance. cc @Wondertan

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1041]
[follow-up] We should create an issue in the go-header so that the genesis block can be handled differently, and so it does not negatively impact the block time in tests and performance. cc @Wondertan

_Originally posted by @nashqueue in https://github.com/rollkit/rollkit/pull/1028#discussion_r1243403037_

**Comment by Manav-Aggarwal** [comment]
Confirm with @gupadhyaya

**Comment by nashqueue** [comment]
I think we can close this issue, as we already made the necessary improvements in go-header.  We just have to double check

**Comment by gupadhyaya** [comment]
fixed via https://github.com/celestiaorg/go-header/pull/87
