### ISSUE TITLE
We shouldn't return an error in case of invalid block. Disussion about when error is appropriate

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#1043]
> I think we need follow-up issue for this. It's not clear what's the best approach here. As we shouldn't just return an error in case of invalid block - this way it's an easy attack vector - you can put something wrong in namespace to discard all valid blocks at given height.

> You're right @gupadhyaya @nashqueue. Anyone can submit any data to the namespace. As the namespace is processed "blob by blob", we need to skip all the "uninteresting" data (aka "trash"). If we can't even deserialize - we don't care - it's a trash for us. If we can deserialize (from protobuf), but can't convert this to our object type - this means something is wrong so we return error.

_Originally posted by @tzdybal in https://github.com/rollkit/rollkit/pull/986#discussion_r1244778417_

**Comment by Manav-Aggarwal** [comment]
Covered by https://github.com/rollkit/rollkit/pull/1301
