### ISSUE TITLE
Change Namespace id to 10 bytes

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#1062]
29 = NamespaceSize = NamespaceVersionSize + NamespaceIDSize - NamespaceVersionZeroPrefixSize = 10
NamespaceVersionSize = 1
NamespaceIDSize = 28
NamespaceVersionZeroPrefixSize = 18
We left pad the namespace with 0s (in celestia-openrpc) so that's why even though Rollkit has 8 it still works.

https://github.com/rollkit/rollkit/blob/main/types/block.go#L16
https://github.com/rollkit/rollkit/blob/main/config/config.go#L96

- [ ] Docs update to use 10 as the namespace id
- [ ] Announce it to all relevant parties as it is a breaking change

**Comment by Manav-Aggarwal** [comment]
This is completely handled in `go-da` now instead of Rollkit. Closing since not relevant anymore.
