### ISSUE TITLE
Modify DA Interface to use SubmitBlobs from SubmitBlocks

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1087]
Need to change the below method across the DA interfaces and implementations:
```go
SubmitBlocks(ctx context.Context, blocks []*types.Block)
```

to have this signature:
```go
SubmitBlobs(ctx context.Context, blobs []*blob.Blob)
```

Currently, the block to blob conversion happens before submitting the blob to a DA layer. We'd like to instead do this conversion before even calling `SubmitBlobs`. This will be useful in https://github.com/rollkit/rollkit/pull/858 which will require the SignedHeader and data in different blobs and potentially even separate namespaces.

Note that the block to blob conversation should happen in `manager.go`.

**Comment by chandiniv1** [comment]
@Manav-Aggarwal Do we need to change signature of SubmitBlock in DA interface?

**Comment by Chirag018** [comment]
@Manav-Aggarwal would like to this up!

**Comment by Manav-Aggarwal** [comment]
Thanks @Chirag018! Just assigned it to you.

**Comment by Chirag018** [comment]
Hey @Manav-Aggarwal, sorry for working on this a little late.

I had a few doubts,

In the manager.go file, the **submitBlocksToDA** function where we will be modifying the changes, do we also need to modify the function name?
```
func (m *Manager) submitBlocksToDA(ctx context.Context) error {
	submitted := false
	backoff := initialBackoff
	for attempt := 1; ctx.Err() == nil && !submitted && attempt <= maxSubmitAttempts; attempt++ {
		res := m.dalc.SubmitBlocks(ctx, m.pendingBlocks.getPendingBlocks())
```

**Comment by Manav-Aggarwal** [comment]
@Chirag018 No worries. Yes, the function name can be modified here if the block-to-blob conversion happens outside of it. Otherwise, it can stay the same.

**Comment by ThanhNhann** [comment]
Hi @Manav-Aggarwal, does this issue still open?

**Comment by Manav-Aggarwal** [comment]
Will be part of #829
