### ISSUE TITLE
Fold the validator roots into the state tree

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#11]
ref: lazyledger/lazyledger-core#66
ref: lazyledger/cosmos-sdk#7

**Comment by liamsi** [comment]
ref:
- https://github.com/celestiaorg/optimint/issues/206
- https://github.com/celestiaorg/optimint/issues/207
- https://github.com/celestiaorg/optimint/issues/205

**Comment by universe2439** [comment]
Test

**Comment by Manav-Aggarwal** [comment]
Since rollkit supports centralized sequencers currently, this is not relevant
