### ISSUE TITLE
Test that Blocksync behaves with lazySeqeuncer the same 

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#1104]
Test that block gossiping has the same behavior with and without block production. 
This test tests two rollup networks against each other.

**Comment by Manav-Aggarwal** [comment]
Tested it, and this issue can be closed once there's a new release with 63486adc5466e067065a0b083cb87c480d8d6d76 included.

**Comment by nashqueue** [comment]
Is there a way to automatically test it?

**Comment by Manav-Aggarwal** [comment]
Not right now. But when there's a will, there's a way.

**Comment by Manav-Aggarwal** [comment]
This is done in `v0.10.4`
> Tested it, and this issue can be closed once there's a new release with [63486ad](https://github.com/rollkit/rollkit/commit/63486adc5466e067065a0b083cb87c480d8d6d76) included.
