### ISSUE TITLE
/status endpoint missing some values

### ISSUE THREAD

**Issue by S1nus** [rollkit/rollkit#1156]
Some values in the `SyncInfo` field of the `ctypes.ResultStatus` [returned by the `FullClient.Status`](https://github.com/rollkit/rollkit/blob/main/node/full_client.go#L739) method are missing. This might break IBC.

### Version of Git SHA

dfae38430c3d9b3d6b2ed822212e960271f71735

### System OS
MacOS
cosmos-sdk  v0.47.3-rollkit-v0.10.1-no-fraud-proofs

### Steps to reproduce it

curl localhost:26657/status

### Expected result

correct values for `latest_block_hash`, `latest_app_hash`, and `earliest_block_hash`

### Actual result

00000000000000000000000000000000

**Comment by jcstein** [comment]
unsure, but flagging in case. #874 may be linked

**Comment by nashqueue** [comment]
We should add those hashes and other fields in the [TestStatus] (https://github.com/rollkit/rollkit/blob/3ae761f66b0b112d7db94c795b8d8fd833f06fe2/node/full_client_test.go#L1003) method

**Comment by gupadhyaya** [comment]
don't see any missing fields `http://localhost:26657/status`

{"jsonrpc":"2.0","id":-1,"result":{"node_info":{"protocol_version":{"p2p":"8","block":"11","app":"1"},"id":"9853a829930eb505a1bab2eaf928c3094d0228ec","listen_addr":"tcp://0.0.0.0:26656","network":"test","version":"1.6.0","channels":"40202122233038606100","moniker":"test","other":{"tx_index":"off","rpc_address":"tcp://0.0.0.0:26657"}},"sync_info":{"latest_block_hash":"1EFFF1EE78E0021B5E53154D6CEDFD33784E39175C01688A53274DD980F6AA7D","latest_app_hash":"9A4952EEC7D858DAE85BADE3FD0FF78DB12542006F410F0D82FC5F1355444D4E","latest_block_height":"3671","latest_block_time":"2024-01-16T10:13:18.573354799Z","earliest_block_hash":"CD4C0FB867A17705ED4B5C4FF78DEB616464572C710F7C99CC37D3D2CBC00DFA","earliest_app_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","earliest_block_height":"1","earliest_block_time":"2024-01-16T04:25:43.249857427Z","catching_up":false},"validator_info":{"address":"489540A144482B7AAF96BCA67E10E27F4A07C501","pub_key":{"type":"tendermint/PubKeyEd25519","value":"qeeZq6eaw2aJk4wkDEiIUzajYjXEtGWJJxzVj7h+lpo="},"voting_power":"5000"}}}
