### ISSUE TITLE
Reject invalid commits in RetrieveLoop

### ISSUE THREAD

**Issue by S1nus** [rollkit/rollkit#1172]
### Implementation ideas

blocks with junk commits / invalid signers can be uploaded to the DA namespace by anyone, so it's best to validate them and discard the invalid ones as soon as possible.

Currently, `processNextDABlock` feeds blocks with invalid headers into `blockInCh`, where they get added to the [`blockCache`](https://github.com/rollkit/rollkit/blob/main/block/manager.go#L321). The header and commit are not checked until `SyncLoop` -> `trySyncNextBlock` -> `applyBlock` -> `ApplyBlock` -> `validate` -> `block.ValidateBasic()` -> `b.SignedHeader.ValidateBasic()`.

**Comment by Manav-Aggarwal** [comment]
Same as audit issue:

```
Late validation of the block from the DA layer may result in overflowing a
node's memory
```

**Comment by S1nus** [comment]
> Same as audit issue:
> 
> ```
> Late validation of the block from the DA layer may result in overflowing a
> node's memory
> ```

even if we fix this in Rollkit, go-header might still have the issue. This is why i wrote this feature https://github.com/celestiaorg/go-header/pull/128 @Wondertan

**Comment by S1nus** [comment]
> Elaborate please. I don't see how go-header can have late validation leading to oom

suppose the height is N, and some junk headers (not signed by the sequencer) arrive on p2p that are height N+1000
doesn't go header store them until the chain catches up? we want to be able to delete them immediately if they aren't signed by the expected proposer
