### ISSUE TITLE
Figure out how to modify RetrieveLoop to catch up with latest DA height faster

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1193]
Currently, the `RetrieveLoop` in Block Manager is responsible for retrieving blocks from the DA layer. It maintains a local version of the DA height, retrieves blocks from that height once every DA block time (~15 seconds) and increments that height. This retrieve mechanism is used for hard confirmations of blocks.

We'd like `RetrieveLoop` to keep up with the latest DA height faster to eliminate this lag.  One way to do this would be to get the latest height, and then retrieve from all heights until that latest height starting from the last height checked plus one. Something similar happens in `BlockRetrieveLoop` currently. Although, we do not have a way to query the DA layer for the latest height in the DA interface so it's not straightforward implement this. 

The `submitBlocksToDA` method does have access to the height that the blocks were published on which is more in sync with the DA layer than the local height so we could use that but this would only keep the height updated for a block producer and not validating full nodes which do not submit blocks to the DA layer. We should figure out an alternative way to pull blocks from all DA heights until the latest height for all types of nodes.

**Comment by gupadhyaya** [comment]
@Manav-Aggarwal i think our previous discussion on inner-looping and retries (https://github.com/rollkit/rollkit/pull/1056#discussion_r1290341238) is relevant here. we could re-introduce some form of retries to reduce the lag.
