### ISSUE TITLE
Automate cosmos-sdk starter release update after new release 

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#1194]
[follow up]
So I think we can automated the branch updates to create the PR and assign it for review. 

If we are creating rollkit releases via the CI, we can add an input for the cosmos sdk version the release is targetting. 

That input value could then be sent with a workflow trigger call to the cosmos sdk to create a new branch, update the go mod and run go mod tidy. 

If that is really all that is needed, then we can automate it pretty easily I think. But if there are often lots of manual touches and edge cases then it might not make sense. 

If the automation makes sense, feel free to turn this into an issue and assign to me.

_Originally posted by @MSevey in https://github.com/rollkit/rollkit/pull/1190#discussion_r1326053996_

**Comment by Manav-Aggarwal** [comment]
Closing this since it is done.
