### ISSUE TITLE
Use DA commitment (obtained using`blob.CreateCommitment`) in DataHash instead of Merkle Hash

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1203]
i think we intend to have the da commitment (obtained using `blob.CreateCommitment` to be stored in DataHash instead of merkle hash, if i am not mistaken @nashqueue?

_Originally posted by @gupadhyaya in https://github.com/rollkit/rollkit/pull/1200#discussion_r1332240392_

Blocked on https://github.com/rollkit/rollkit/issues/1087. Since DataHash is set in Block Manager, there needs to be a way to compute DA commitments in Block Manager.

**Comment by nashqueue** [comment]
Not really blocked on #1087 just in conflict. We don't need Submitblobs to create commitment.

**Comment by Manav-Aggarwal** [comment]
Will be part of https://github.com/rollkit/rollkit/issues/829
