### ISSUE TITLE
Test full node catching up when far behind with blocks having lots of Txs

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1213]
That means if I sync and I am far behind, I would be able to sync fully no matter the height difference. I think we should test how the sync of a chain (with a lot of txs) performs. Can be a follow-up. VA

_Originally posted by @nashqueue in https://github.com/rollkit/rollkit/pull/1204#discussion_r1339321177_

**Comment by ThanhNhann** [comment]
Hi @Manav-Aggarwal, I see in the document of `BlockStoreRetrieveLoop`, it says `It keeps track of the last retrieved block's height and every time the current block store's height is greater than the last retrieved block's height, it retrieves all blocks from the block store that are between these two heights` but in the code we are set [lastBlockStoreHeight](https://github.com/rollkit/rollkit/blob/9cbe7dcac74b679eec7fa38b7cdc86ccb5f316d6/block/manager.go#L479) = 0, so It will always retrieve from 0 to current block store's height, should we add a param in like `startHeightRetrive` in `Manager.BlockStoreRetrieveLoop` func ?

**Comment by Roockeeeet** [comment]
test: test P2P catchup
rollkit/rollkit
