### ISSUE TITLE
specs: describe success/failure scenarios for DA submission

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#1236]
If we submit a block, what qualifies it as being successfully submitted? What from the following scenarios is a successful submission:
- submitting the Celestia transaction (rollup Block) into the mempool
- submitting the Celestia transaction (rollup Block) into the mempool, but there is a nonce clash with a different transaction but the same nonce but different transaction. Example PFB submission plus TIA transfer using the same nonce. The one from rollkit will fail and never be included
- submitting the Celestia transaction (rollup Block) but the gas was misconfigured too low so it will be stuck in the mempool
- we call submit but get no response (node crashed for example)
- we submit a tx but it is impossible to fit as it is too big (too many bytes) so it fails

**Comment by nashqueue** [comment]
Switched this to Va

**Comment by gupadhyaya** [comment]
Fixed in https://github.com/rollkit/rollkit/pull/1308
