### ISSUE TITLE
DA submission should check for successful inclusion

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#1241]
The issue is that we will have 2 transactions with the same nonce. So that means that if for some reason the first transaction gets included than the 15 blocks transaction get rejected and 5 blocks will be in limbo.

**Comment by nashqueue** [comment]
Corresponding thread for context : _Originally posted by @nashqueue in https://github.com/rollkit/rollkit/pull/1202#discussion_r1338631649_

**Comment by Manav-Aggarwal** [comment]
Same as audit issue

`Rollup block not published in the DA layer`
