### ISSUE TITLE
ERROR failed while querying src chain for latest height: RPC error to endpoint

### ISSUE THREAD

**Issue by chandiniv1** [rollkit/rollkit#1255]
### Version of Git SHA

v0.10.4

### System OS

ubuntu

### Installed tools

**cosmos-sdk**

- github.com/rollkit/cosmos-sdk v0.47.3-rollkit-v0.10.4-no-fraud-proofs

**Ignite version**

- v0.27.1

**Hermes version**

-  v1.6.0+1c1cf02

### Others

**hermes config**
```

[global]
log_level = 'info'
[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true
[mode.connections]
enabled = true
[mode.channels]
enabled = true
[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true
[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001
[rest]
enabled = true
host    = '127.0.0.1'
port    = 3000

[[chains]]
id = 'gm-chain-2'
rpc_addr = 'http://localhost:16657'
grpc_addr = 'http://localhost:9092'
event_source = { mode = 'push', url = 'ws:/localhost:16657/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'gm1'
key_name = 'gm-1'
store_prefix = 'ibc'
gas_price = { price = 0.01, denom = 'stake' }
max_gas = 10000000
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'gm'
rpc_addr = 'http://localhost:26657'
grpc_addr = 'http://localhost:9090'
event_source = { mode = 'push', url = 'ws:/localhost:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'gm1'
key_name = 'gm-key-1'
store_prefix = 'ibc'
gas_price = { price = 0.01, denom = 'stake' }
max_gas = 10000000
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
```

### Steps to reproduce it

hermes create channel --a-chain gm --b-chain gm-chain-2 --a-port transfer --b-port transfer --new-client-connection

### Expected result

It should create client ,connection and channel between the chains.

### Actual result

![Screenshot from 2023-10-17 12-08-28](https://github.com/rollkit/rollkit/assets/117723967/b456f6db-7180-4ba6-9b67-c5f557b55e58)

### Relevant log output

```Shell
ERROR ThreadId(01) foreign_client.create{client=gm-chain-2->gm:07-tendermint-0}: failed to create client: error raised while creating client for chain gm-chain-2: failed while querying src chain for latest height: RPC error to endpoint http://localhost:16657/: HTTP error: connection closed before message completed
ERROR error raised while creating client for chain gm-chain-2: failed while querying src chain for latest height: RPC error to endpoint http://localhost:16657/: HTTP error: connection closed before message completed
```

**Comment by nashqueue** [comment]
The error is related to #1156

**Comment by chandiniv1** [comment]
@nashqueue when I tried to create a  channel with `--debug=rpc` flag, I found that  hermes relayer is making request for `header `method with` height` as param for the node since header method is not accessible, connection is closing.Hope you consider this,
Thank you

**Comment by gupadhyaya** [comment]
we only support rollkit v0.11.x which is compatible with comet 38 and cosmos-sdk v0.50.x. i checked hermes (gaia) only works for cosmos-sdk v0.45.x (v0.46.x, and v0.47.x). hence, cannot test this. closing the issue for now and we can reopen when the support is added. @chandiniv1
