### ISSUE TITLE
Add Test for Health RPC Call in full_client_test.go

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#1258]
## Description

Currently, there is no explicit test for the Health RPC call in `full_client_test.go`. The Health RPC call is crucial for monitoring the status of the node and ensuring its proper functioning.

## Expected Behavior

A test should be added to `full_client_test.go` that calls the Health RPC and asserts that the response is as expected. The test should check for an empty response, which indicates that the node is healthy.

## Additional Context

According to the [CometBFT RPC documentation](https://docs.cometbft.com/v0.38/spec/rpc/), the Health RPC call doesn't have any parameters and returns an empty response if the node is healthy.

**Comment by KekmaTime** [comment]
@nashqueue i would like to work on this issue

**Comment by nashqueue** [comment]
Thank you for your contributions! I think @chandiniv1 already took this one up. So I will assign it to her.
