### ISSUE TITLE
Enhance TestStatus function in full_client_test.go

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#1259]
### Description:
The `TestStatus` function in `full_client_test.go` currently checks for no errors and validates some of the returned values from the Status RPC call. However, it does not verify all the fields in the response. 

### Task:
Enhance the `TestStatus` function to include checks for all the fields in the response. Specifically, add assertions to check the `SyncInfo` and `ValidatorInfo` fields in the response. 

### Acceptance Criteria:
- The `TestStatus` function should include checks for all fields in the Status RPC response.
- The test should pass all assertions, indicating that the Status RPC call is functioning as expected and returning the correct data.

**Comment by KekmaTime** [comment]
@nashqueue can i assign me this issue? i feel i can do this!
