### ISSUE TITLE
Improve TestBlockchainInfo in full_client_test.go

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#1261]
### Description
The current `TestBlockchainInfo` function in `full_client_test.go` only checks the correctness of  `LastHeight` and that it contains  `BlockMetas` but not the contents of it returned `BlockchainInfo`. To ensure full compliance with the CometBFT RPC specification, we should extend this test to verify all fields in the returned `BlockchainInfo`.

### Steps to Improve
1. Update the `TestBlockchainInfo` function to check all fields in the returned `BlockchainInfo` against the expected values. This includes fields like `block_id`, `block`, `header`, `data`, `evidence`, and `last_commit`.

2. For each field, add assertions to check if the returned value matches the expected value. Use the `assert.Equal` function for this.

3. Run the test to ensure it passes with the new assertions.

### Expected Outcome
The `TestBlockchainInfo` function should now fully validate the `BlockchainInfo` returned by the RPC call, ensuring it matches the CometBFT RPC specification. https://docs.cometbft.com/v0.38/spec/rpc/

**Comment by KekmaTime** [comment]
@nashqueue i would like to work on this issue
