### ISSUE TITLE
Investigate strange checks in SignedHeader.Verify

### ISSUE THREAD

**Issue by S1nus** [rollkit/rollkit#1270]
SignedHeader.Verify has some [unclear checks](https://github.com/rollkit/rollkit/blob/main/types/signed_header.go#L52). Investigate the purpose of this, determine the intended behavior, and make sure it behaves as expected.

**Comment by Manav-Aggarwal** [comment]
Closed by https://github.com/rollkit/rollkit/pull/1301/
