### ISSUE TITLE
Rename Store Interface `Load` methods to be `Get` instead for clarity

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1284]
Yea let's make a follow up to rename to `Get`

_Originally posted by @MSevey in https://github.com/rollkit/rollkit/pull/1265#discussion_r1374664992_

**Comment by nashqueue** [comment]
I would keep it Load https://github.com/cometbft/cometbft/blob/main/store/store.go#L139 to ensure we don't change much from comet as that will keep the parity easier. I am open to changing things but then we can look into options of rewriting the store instead of just refactors.

**Comment by Manav-Aggarwal** [comment]
cc: @MSevey

**Comment by MSevey** [comment]
> I would keep it Load https://github.com/cometbft/cometbft/blob/main/store/store.go#L139 to ensure we don't change much from comet as that will keep the parity easier. I am open to changing things but then we can look into options of rewriting the store instead of just refactors.

I'd agree with this more if the methods were truly copy paste but it seems like we have already deviated slightly.

This is a low priority, more of a semantic naming nit, so I'm ok with delaying this to when we have more work planned for the store.
