### ISSUE TITLE
Make a decision ABCI vs Rollkit to decide the current proposer

### ISSUE THREAD

**Issue by S1nus** [rollkit/rollkit#1291]
This is underspecified and requires a final decision before we proceed. There are two options, the tradeoffs emerge in the form of how "key rotations" would be implemented.

**1. Rollkit decides the proposer**
**Pro**
We could very easily enforce centralized sequencers in Rollkit with minimal changes to the code. This would prevent user-error from ABCI app devs.
**Con**
No mechanism for sequencer key rotations. We'd need to add a feature for that in Rollkit, OR we do nothing and simply let the rollup devs handle sequencer key rotations via hard-forks, which might not be so bad for the `vA` release. 

**2. ABCI decides the proposer**
**Pro**
Responsibility for sequencer key rotation feature is shifted from Rollkit up to the ABCI App
**Con**
- We would need to pay more attention to the cosmos-sdk to prevent user-error
- We would need to write a key rotations module in cosmos-sdk to replace the staking module.
- we don't currently have any cosmos-sdk code for this, nor do we have plans to develop and audit such a thing

**Comment by Manav-Aggarwal** [comment]
In favor of Rollkit deciding the proposer

**Comment by S1nus** [comment]
> In favor of Rollkit deciding the proposer

PR in the works

**Comment by MSevey** [comment]
> In favor of Rollkit deciding the proposer

Agreed, seems like the ABCI option has the same and more cons.
