### ISSUE TITLE
Understand constants in the mempool tests

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1305]
#1304 fixed a mempool test failure by changing a hardcoded constant, however it isn't understood where the original constant came from.

We need to understand the constants referenced in these two comments:

https://github.com/rollkit/rollkit/pull/1304#discussion_r1378839745

https://github.com/rollkit/rollkit/pull/1304#discussion_r1378845107

**Comment by gupadhyaya** [comment]
`mempool/v1/mempool_test.go` no longer exists in the main branch as v0.11.x mempool refactor removed it. So, the comments about the constants is not relevant. However, I have added some context regarding the two comments in the links below.
https://github.com/rollkit/rollkit/pull/1304#discussion_r1462819248
https://github.com/rollkit/rollkit/pull/1304#discussion_r1462831680
