### ISSUE TITLE
Use strechr/testify assert instead of creating new assert for consistency

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1320]
The reason I didn't touch that was to manage scope creep on this PR. 
    In general I think it is cleaner and more flexible to pass the `testing.T` around vs `assert` or `require` but I didn't want 
    to edit `gerPeerID` and the verify helpers in this PR. 

    This could be a follow up if we wanted, but it is pretty low priority to do this type of testing clean up so we should 
    probably just leave it for now.

_Originally posted by @MSevey in https://github.com/rollkit/rollkit/pull/1313#discussion_r1388221661_

**Comment by trinitys7** [comment]
Hi sir @Manav-Aggarwal , can I take this issue?

**Comment by Manav-Aggarwal** [comment]
Of course, just assigned it to you, thanks for taking it! @trinitys7
