### ISSUE TITLE
The `New` method should be a package-level function rather than a method on the `SignedHeader` struct, as it does not depend on an instance of `SignedHeader`. This is more idiomatic in Go.

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1340]
The `New` method should be a package-level function rather than a method on the `SignedHeader` struct, as it does not depend on an instance of `SignedHeader`. This is more idiomatic in Go.
```diff
- func (sh *SignedHeader) New() *SignedHeader {
+ func NewSignedHeader() *SignedHeader {
    return new(SignedHeader)
}
```

---

<details>
<summary>Commitable suggestion</summary>

> [!IMPORTANT]
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation.

```suggestion
func NewSignedHeader() *SignedHeader {
    return new(SignedHeader)
}
```

</details>

_Originally posted by @coderabbitai[bot] in https://github.com/rollkit/rollkit/pull/1294#discussion_r1393880845_

**Comment by Manav-Aggarwal** [comment]
This is so that `SignedHeader` implements the interface for `go-header`. So this is required.

**Comment by Wondertan** [comment]
Yes, @MSevey check the Header interface New method that mentions why this is needed. Basically because ‘new(T)’ in generic code doesn't give you an instantiated value
