### ISSUE TITLE
Handle cases other than Initial Height 1 in genesis file

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1360]
Same as audit issue:

```
Rollkit chain is initialized properly only if InitialHeight is 1 in the genesis
file
```

**Comment by S1nus** [comment]
If the purpose of supporting heights != 1 is to enable hard-forks, then we don't do that yet.

Here, you can see that [we ignore the genesis](https://github.com/rollkit/rollkit/blob/main/block/manager.go#L104) if `store.GetState()` succeeds. Rather, we should consider loading the state from genesis if it has a higher height, and possibly override the store and revert back if it mismatches with what's stored at that height.
