### ISSUE TITLE
Investigate potential OOM leak

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1389]
I just realized that Rollkit has [the same leak](https://github.com/celestiaorg/celestia-node/issues/2905#issuecomment-1826451690) as celestia-node and IPFS, as you use the combination of libp2p's DHT and badger(dht triggers unhandled edge case in badger)
I recommend migrating to v4 of Badger and using [our fork](https://github.com/celestiaorg/badger) and [adapter](https://github.com/celestiaorg/go-ds-badger4/). I can also help you with auditing your badger configuration for performance. - @Wondertan

**Comment by S1nus** [comment]
We are using an old version of Badger, and should ideally use `[go-ds-badger4](https://github.com/celestiaorg/go-ds-badger4)` from `celestia-node`. It [seems](https://github.com/celestiaorg/go-ds-badger4/blob/master/datastore.go#L143) to be compatible with the [interface we use](https://github.com/celestiaorg/go-ds-badger4/blob/master/datastore.go#L143)
