### ISSUE TITLE
Use prometheus in rollkit

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#1393]
Currently rollkit uses no instrumentation or metrics such as prometheus: https://github.com/rollkit/rollkit/blob/main/node/full.go#L180. We need to adopt premetheus like cometbft, such that apps that wants to use prometheus and are passing some premetheus configuration in `config.toml` can take advantage of it.

```
#######################################################
###       Instrumentation Configuration Options     ###
#######################################################
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "cometbft"
```

Refer to cometbft for adding premetheus support.

**Comment by Olshansk** [comment]
@gupadhyaya Do you think we'll have this enabled before the new year or is it something for after the holidays?

**Comment by gupadhyaya** [comment]
the scope of the work is slightly larger and we are working on it. Fyi, we are working towards adding these:

1. Directly port following metrics from cometbft:
* abci/app: https://github.com/rollkit/cometbft/blob/main/proxy/metrics.go
* mempool: https://github.com/rollkit/cometbft/blob/main/mempool/metrics.go 
* state machine/executor: https://github.com/rollkit/cometbft/blob/main/state/metrics.go
* p2p: https://github.com/rollkit/cometbft/blob/main/p2p/metrics.go

2. block & header sync metrics from go-header library 

3. replace consensus metrics with sequencer metrics

in terms of the timeline, we are aiming after the holidays. Should be done in the first week of jan.

**Comment by Olshansk** [comment]
@okdas FYI ☝️
