### ISSUE TITLE
Enforce rollup block size is less than DA.MaxBlobSize

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1428]
Same as audit issue:

`Large rollup blocks may compromise liveness`

**Comment by Manav-Aggarwal** [comment]
refer to `createBlock`

**Comment by tzdybal** [comment]
I think that modification of max block size should be made during block production, without touching genesis. We shouldn't modify genesis IMHO - it's the human consensus.
Additionally, `MaxBlobSize` is dynamic. Later in time it can be changed (e.g. after DA update). If genesis is modified, `ConsensusParams` needs to be updated manually to adopt to change in `MaxBlobSize`. Rollup operators needs to know that block size in consensus was modified (probably long time ago).

In my opinion, we should approach this problem by using `min(ConsensusParams.Block.MaxBytes, MaxBlobSize - overhead)` during block creation.
