### ISSUE TITLE
Compute IsProposer once

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1452]
IsProposer can be computed at startup and that’d never change
over the course of the program lifecycle.

See BB audit issue:

`Finding 020 - Compute IsProposer once`

**Comment by Manav-Aggarwal** [comment]
Keeping as method is okay

**Comment by Manav-Aggarwal** [comment]
Can be computed as a `bool` once in `NewManager` and then used later.

**Comment by MuhtasimTanmoy** [comment]
Would like to work on this
