### ISSUE TITLE
store: key not found error

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#147]
Problem: currently, there is no easy way to distinguish "key not found" situation, from other `KVStore` errors.

Tasks:
- [ ] create `ErrKeyNotFound` sentinel variable
- [ ] properly handle `badger.ErrKeyNotFound`
- [ ] properly handle "key not found situation" in `da/mock` package (after #146)

**Comment by pmareke** [comment]
I'll give it a try, tell me what you think!
