### ISSUE TITLE
PendingBlocks#getPendingBlocks Simplification

### ISSUE THREAD

**Issue by newTendermint** [rollkit/rollkit#1482]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-5f1fc6a3-7fff-f98a-a58c-53accbb14e45"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Roboto,sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Finding 002 - PendingBlocks#getPendingBlocks Simplification</span></h3><div dir="ltr" style="margin-left:0pt;" align="left">
ID | 002
-- | --
Finding | PendingBlocks#getPendingBlocks Simplification
Severity | 1 - Informational
Description | The method getPendingBlocks on the PendingBlocks creates a shallow copy of the blocks and sorts them. A manual copy of the slice can be avoided.
Recommendation | Consider calling the built-in slices.Clone method which returns a shallow copy instead.
Code References | https://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/block/pending_blocks.go#L29-L32

</div></b>

**Comment by Manav-Aggarwal** [comment]
Although doing a shallow copy improves performance, it's safer to do a deep copy here so the mutex on `pendingBlocks` can be released and not held while sorting it.
