### ISSUE TITLE
Context as a Field in HeaderSyncService and BlockSyncService

### ISSUE THREAD

**Issue by oxnr** [rollkit/rollkit#1483]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-79db3b95-7fff-89a7-3f36-f3c1a59d0d57"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Roboto,sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Finding 003 - Context as a Field in HeaderSyncService and BlockSyncService</span></h3><div dir="ltr" style="margin-left:0pt;" align="left">
ID | 003
-- | --
Finding | Context as a Field in HeaderSyncService and BlockSyncService
Severity | 2 - Informational
Description | Both the HeaderSyncService and BlockSyncService types have a Context field as part of the type. Many methods on these types accept a Context argument from the caller, which is ideal. Not only does this make the internal Context field unnecessary, it’s also an indication of a codesmell and should be removed.
Recommendation | As most of the methods already accept Context as an argument, remove the Context field from both HeaderSyncService and BlockSyncService. For methods that do not accept a Context, update them to accept a Context from the caller in order to manage lifecycle events properly, e.g. Start.
Code References | https://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/block/header_sync.go#L44https://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/block/block_sync.go#L43

</div></b>

**Comment by Manav-Aggarwal** [comment]
Need to make the change in https://github.com/celestiaorg/go-header/ since `HeaderSyncService` and `BlockSyncService` implement the `go-header` interface.

**Comment by AryanGodara** [comment]
@Manav-Aggarwal Is this an issue that we can propose to the `go-header` project?
It'll be an interesting issue to tackle across repositories

**Comment by Wondertan** [comment]
> HeaderSyncService and BlockSyncService implement the go-header interface.

These services do not implement any of the interfaces defined in go-header. Furthermore, interfaces can't enforce storing a ctx field on the struct, so I don't think this is related to go-header anyhow.
