### ISSUE TITLE
Refactor GenerateKey to be more robust

### ISSUE THREAD

**Issue by newTendermint** [rollkit/rollkit#1492]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-41fe34dd-7fff-2633-306b-38f1fb8d25db"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Roboto,sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Finding 028 - Refactor GenerateKey to be more robust</span></h3><div dir="ltr" style="margin-left:0pt;" align="left">
ID | 028
-- | --
Finding | Refactor GenerateKey to be more robust
Severity | 0 - Informational
Description | GenerateKey simply uses `fmt.Sprintf(“%v”, field”)` to convert a part of a multipart key into bytes. This is not robust, it is also most likely not computationally and space efficient. Also the API is unbounded by the usage of `interface{}`  which means that also non-deterministic formattable values could be passed to it.
Recommendation | Make the API more robust, or constrain the accepted types to a smaller set.
Code References | https://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/store/kv.go#L44

</div></b>

**Comment by MuhtasimTanmoy** [comment]
Would like to work on this

**Comment by AbhinavMir** [comment]
Hi, first time contributor: Does [this](https://github.com/rollkit/rollkit/pull/1526) look good? Thanks!

**Comment by AryanGodara** [comment]
@Manav-Aggarwal Could you please assign this one to me :D
