### ISSUE TITLE
Header Verification

### ISSUE THREAD

**Issue by newTendermint** [rollkit/rollkit#1495]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-646a3ae3-7fff-cc14-323c-1dfa496ec5cf"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Roboto,sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Finding 032 - Header Verification</span></h3><div dir="ltr" style="margin-left:0pt;" align="left">
ID | 032
-- | --
Finding | Header Verification
Severity | 2 - Informational
Description | The Verify method defined on the Header type is lacking any verification or validation outside of checking the aggregator hashes. It’s not clear if this method is expected to verify more, but there is an unresolved TODO without any reference issue link. This might add to technical debt as this particular part of the codebase evolves.
Recommendation | Consider removing the TODO in what seems to be a critical method on the Header type and/or consider expanding upon verification and validation of the header compared to the untrusted header, such as ChainID and Version. At the very least, there should be a clear godoc on the method that describes what verification is expected to perform.
Code References | https://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/types/header.go#L82

</div></b>

**Comment by Manav-Aggarwal** [comment]
TODO removed.
