### ISSUE TITLE
Incorrect Untrusted Header height validation

### ISSUE THREAD

**Issue by oxnr** [rollkit/rollkit#1496]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-94d87bae-7fff-d5f2-2bab-c7a4f70b855c"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Roboto,sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Finding 036 - Incorrect Untrusted Header height validation</span></h3><div dir="ltr" style="margin-left:0pt;" align="left">
ID | 036
-- | --
Finding | Incorrect Untrusted Header height validation
Severity | 0 - Informational
Description | Untrusted header height is expected to be >= the trusted header but in reality it should just be == to trusted header +1.
Recommendation | Fix the validation step to do an equality check.
Code References | https://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/types/signed_header.go#L54

</div><br /><br /></b>

**Comment by Manav-Aggarwal** [comment]
Making the change from `>= the trusted header` to == `trusted header +1` causes issues with https://github.com/celestiaorg/go-header. Needs more investigation.
