### ISSUE TITLE
[Feature Request][da]: gracefully handle submit mempool errors

### ISSUE THREAD

**Issue by tuxcanfly** [rollkit/rollkit#1522]
### Implementation ideas

If a DA submit tx is pending in the mempool, we should not retry with backoff because we'll exhaust all retries. Instead, we should wait until the tx is dropped from the mempool and _then_ retry.

Examples of mempool errors which should be gracefully handled:

* account sequence mismatch
* tx already subscribed
* tx already exists in cache

**Comment by Wondertan** [comment]
I believe this logic should be built into core/node stack as there is more info on how to handle those cases.

If Rollkit wants to handle these for all the supported DAs through the go-da, then we would need standardise such errors on the go-da interface level  so retry logic could detect them. The DAs impls would neeed to adapt internal errors to the defined interface one.

Potentially, this retry could live in go-da repo.
