### ISSUE TITLE
rollkit 0.12 doesn't exist

### ISSUE THREAD

**Issue by pepyakin** [rollkit/rollkit#1562]
Just as heads up there is some problem with released version of rollkit.

It looks like 0.11.19 is the latest release. However, pkg.go.dev shows 0.12 as released back in november.

https://pkg.go.dev/github.com/rollkit/rollkit@v0.11.19?tab=versions

In Rust land you usually yank. Not sure what's the best way of action in this case.

**Comment by tzdybal** [comment]
We probably should [retract](https://go.dev/ref/mod#go-mod-file-retract) this version.
