### ISSUE TITLE
Revisit posibly duplicated setup of `dalc` in tests

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#1571]
Why those lines are introduced? `dalc` is already passed to `createAndConfigureNode`?

_Originally posted by @tzdybal in https://github.com/rollkit/rollkit/pull/1544#discussion_r1504804404_

**Comment by AryanGodara** [comment]
@tzdybal, I'll fix this one and #1572 in a new common PR, I'm working on it rn and will push it today after reviewing my code more carefully this time 🧐
Can you please assign it to me, so there are no conflicts with competing PRs :)
