### ISSUE TITLE
Inconsistent code/comments in `TestStatus`

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#1572]
Comment states that node doesn't need to start, but newly introduced code starts node.

This is probably unnecessary - see: https://github.com/rollkit/rollkit/pull/1544/files#diff-d751652dbf6a9ef1932a52cb8eed06e3c49a830cb43c80a37f452c9a650b296dR881

_Originally posted by @tzdybal in https://github.com/rollkit/rollkit/pull/1544#discussion_r1504795303_

**Comment by tzdybal** [comment]
@AryanGodara you need to comment here, otherwise I'm not able to assign yoo

**Comment by AryanGodara** [comment]
Commenting to get assigned :D

**Comment by Manav-Aggarwal** [comment]
Fixed by https://github.com/rollkit/rollkit/pull/1577
