### ISSUE TITLE
[ibc] block height mismatch error in gm rollup

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#1573]
Randomly getting this panic which is making GM rollup crash. This is happening on the main branch. Possibly some regression introduced? 
```
panic: block height mismatch

goroutine 294 [running]:
github.com/rollkit/rollkit/block.(*Manager).publishBlock(0x1400073a780, {0x106001568, 0x14002314aa0?})
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/block/manager.go:745 +0xc44
github.com/rollkit/rollkit/block.(*Manager).AggregationLoop(0x1400073a780, {0x106001568, 0x14002314aa0}, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/block/manager.go:290 +0x1fc
github.com/rollkit/rollkit/node.(*FullNode).OnStart.func1()
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/node/full.go:384 +0x30
github.com/rollkit/rollkit/types.(*ThreadManager).Go.func1()
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/types/threadmanager.go:26 +0x58
created by github.com/rollkit/rollkit/types.(*ThreadManager).Go in goroutine 1
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/types/threadmanager.go:24 +0x7c
```

**Comment by gupadhyaya** [comment]
Did some more investigation and it looks like this panic only happens when doing ibc transfer. 

The command that resulted in panic: 
`gmd tx ibc-transfer transfer transfer channel-0 osmo1vvl79phavqruppr6f5zy4ypxy7znshrqm390ll 1000000stake --node tcp://localhost:36657 --chain-id gm --from gm-key --keyring-backend=test --fees 5000stake`

printed some logs around the panic:
```
if state.LastBlockHeight > 0 && block.Height() != state.LastBlockHeight+1 {
		fmt.Println("state.LastBlockHeight", state.LastBlockHeight, "block.Height()", block.Height())
		return errors.New("block height mismatch")
}
```
```
state.LastBlockHeight 4822 block.Height() 4822
panic: block height mismatch

goroutine 76 [running]:
github.com/rollkit/rollkit/block.(*Manager).publishBlock(0x140009323c0, {0x10475d588, 0x140029f2cd0?})
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/block/manager.go:745 +0xc44
github.com/rollkit/rollkit/block.(*Manager).AggregationLoop(0x140009323c0, {0x10475d588, 0x140029f2cd0}, 0x0)
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/block/manager.go:290 +0x1fc
github.com/rollkit/rollkit/node.(*FullNode).OnStart.func1()
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/node/full.go:384 +0x30
github.com/rollkit/rollkit/types.(*ThreadManager).Go.func1()
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/types/threadmanager.go:26 +0x58
created by github.com/rollkit/rollkit/types.(*ThreadManager).Go in goroutine 1
	/Users/gupadhyaya/go/src/github.com/gupadhyaya/rollkit/types/threadmanager.go:24 +0x7c
```
Restarting GM rollup and redoing all the steps of ibc transfer seems to be working.

**Comment by vuong177** [comment]
[Store height](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/store/store.go#L30) can be set to current state [LastBlockHeight](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/types/state.go#L37) by call [GetState()](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/store/store.go#L193). 

So there's a potential vectors that make rollkit sequence halt :
 1. When publish block n, between [update store height](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/block/manager.go#L775) and  update new state via [updateState](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/block/manager.go#L806), set the `store height` to old state height (n-1) by call `GetState`.
 2. When publish block n+1, current block height is `n-1` instead of `n`. It lead to block mismatch err `block.Height() != state.LastBlockHeight+1`
 
 I suggest we should seperate state height and block height in [DefaultStore](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/store/store.go#L28). It should be : 
 ```
 type DefaultStore struct {
	db     ds.TxnDatastore
	blockHeight atomic.Uint64
	stateHeight atomic.Uint64
}
 ```

**Comment by vuong177** [comment]
btw for quick re-produce this panic, you should set `--rollkit.block_time` to 0.1s when start gmd

**Comment by gupadhyaya** [comment]
@vuong177  i was not able to reproduce on GM app with latest rollkit: https://github.com/rollkit/cosmos-sdk/releases/tag/v0.50.1-rollkit-v0.12.0-rc0-no-fraud-proofs
can you try with latest rollkit?
my gmd start command is:
```
gmd start --rollkit.aggregator --rollkit.da_address=":26650" --rollkit.da_start_height $DA_BLOCK_HEIGHT --rpc.laddr tcp://127.0.0.1:36657 --p2p.laddr "0.0.0.0:36656" --minimum-gas-prices="0.025stake" --rollkit.da_namespace 00000000000000000000000000000000000000000008e5f679bf7116cb --rollkit.da_gas_price 0.2 --rollkit.da_gas_multiplier 1.2 --rollkit.block_time 0.1s
```

**Comment by vuong177** [comment]
@gupadhyaya I'm using the same version with you, in my `go.mod` :
```
	pgregory.net/rapid v1.1.0 // indirect
	sigs.k8s.io/yaml v1.4.0 // indirect
)

replace github.com/cosmos/cosmos-sdk => github.com/rollkit/cosmos-sdk v0.50.1-rollkit-v0.12.0-rc0-no-fraud-proofs
```
my gmd start :
```
gmd start --rollkit.aggregator --rollkit.da_address=:26650 --rollkit.da_start_height $DA_BLOCK_HEIGHT --rpc.laddr tcp://127.0.0.1:36657 --grpc.address 127.0.0.1:9290 --p2p.laddr "0.0.0.0:36656" --minimum-gas-prices=0.025stake --rollkit.block_time 0.1s
```

**Comment by vuong177** [comment]
I ran several time and always get panic 

```
1:36PM INF indexed block events height=68 module=txindex
1:36PM INF Using pending block height=68 module=BlockManager
panic: block height mismatch

goroutine 251 [running]:
github.com/rollkit/rollkit/block.(*Manager).publishBlock(0x140007963c0, {0x108836848, 0x14002975360?})
        /Users/vuongnguyen/go/pkg/mod/github.com/rollkit/rollkit@v0.12.0-rc0/block/manager.go:753 +0xc44
github.com/rollkit/rollkit/block.(*Manager).AggregationLoop(0x140007963
```

**Comment by gupadhyaya** [comment]
whats the DA are you using? local-celestia-devnet? i am using https://github.com/rollkit/local-celestia-devnet/releases/tag/v0.12.7

i copy pasted your command and started fresh gm repo and still not able to reproduce.

**Comment by vuong177** [comment]
I'm using v0.12.7
```
➜  ~ docker run -t -i --platform linux/amd64 -p 26650:26650 -p 26657:26657 -p 26658:26658 -p 26659:26659 -p 9090:9090 ghcr.io/rollkit/local-celestia-devnet:v0.12.7
```

**Comment by vuong177** [comment]
Let me try with another machine

**Comment by vuong177** [comment]
@gupadhyaya you will get this panic more frequently if you create an IBC channel.

**Comment by gupadhyaya** [comment]
> [Store height](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/store/store.go#L30) can be set to current state [LastBlockHeight](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/types/state.go#L37) by call [GetState()](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/store/store.go#L193).
> 
> So there's a potential vectors that make rollkit sequence halt :
> 
> 1. When publish block n, between [update store height](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/block/manager.go#L775) and  update new state via [updateState](https://github.com/vuong177/rollkit/blob/18dc8d32555ecfb754d2327dc3ff2711bc7851f1/block/manager.go#L806),it's possible to set the `store height` to old state height (n-1) by call `GetState`.
> 2. When publish block n+1, current block height is `n-1` instead of `n`. It lead to block mismatch err `block.Height() != state.LastBlockHeight+1`

but we never restart the manager, hence i don't think it is the reason. 

however from your logs:
```
1:36PM INF indexed block events height=68 module=txindex
1:36PM INF Using pending block height=68 module=BlockManager
panic: block height mismatch
```
we can see that `Using pending block`, which means that we have a case where the block was successfully published, but `m.store.Height` was not update. my guess that since aggregate loop runs on its own thread, the ibc call could have crashed the goroutine and restarted it to last in-memory state (note that height is not disk persisted, it is only in-memory). 

i think the fix could be to push the store height to disk instead of in-memory. in which case there should not be any inconsistencies.

**Comment by vuong177** [comment]
@gupadhyaya It can happen without restarting the node, right? Any call to `GetState` will set in-memory block height to state height in disk. I think we should avoid calling setHeight in the get method.
btw, relayer call `GetState` many times by query `ConsensusParam`, it's reason that relayer make this node panic more frequently.

**Comment by gupadhyaya** [comment]
Thanks for the clarification.  Make sense. @vuong177
