### ISSUE TITLE
Add support for vote extensions

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#1593]
Following ABCI methods needs to be supported in rollkit
```
ExtendVote(context.Context, *types.RequestExtendVote) (*types.ResponseExtendVote, error)
VerifyVoteExtension(context.Context, *types.RequestVerifyVoteExtension) (*types.ResponseVerifyVoteExtension, error)
```

**Comment by gupadhyaya** [comment]
may be another relevant example:
https://github.com/skip-mev/vote-ext-oracle-demo

**Comment by tzdybal** [comment]
Notes:
1. `Vote Extension` is kind a artificial addition to rollkit - it's core definition is very close to CometBFT consensus voting phase. There is no voting in rollkit, so it's hard to "extend" it.
2. As currently only single sequencer is supported there is no peer in the network to run 'VerifyVoteExtension`.
3. Apart from compatibility (which is crucial), I can't see much value in vote extension in single sequencer scenario - data could be pulled/used during proposal processing directly, without using vote extension.
   * One of typical examples is to provide some data in vote extensions by multiple validators and then calculate average  during proposal processing. With single validator/sequencer - this makes no sense.
4. In the future (when multiple sequencers are supported) gossiping of vote extensions should be implemented.
   * It should be possible (but probably not practical) to implement support for vote extensions gossiping even for single sequencer scenario, and this would invalidate point 3 above.

**Comment by Manav-Aggarwal** [comment]
Agree with all these points, this is mainly for compatibility reasons.

> data could be pulled/used during proposal processing directly, without using vote extension.

Yes, doing it in PrepareProposal/ProcessProposal is also possible but adds overhead of users that already have it with VoteExtensions needing to maintain another fork that uses this instead of VoteExtensions.
