### ISSUE TITLE
Explore and define Optimint state transition fraud proof requirements

### ISSUE THREAD

**Issue by adlerjohn** [rollkit/rollkit#160]
There are a number of questions that need to be answered around how Optimint (and optimistic rollups in general on Celestia) will deal with state transition fraud proofs. 

- [ ] What restrictions would be needed to be placed on the Cosmos SDK to have state transition fraud proofs, and how much would that impact UX and cost? 
- [ ] Can we use state transition fraud proofs for the EVM, or do we need to use Interactive Verification Games (IVGs)?
- [ ] Can we use a WASM-based IVG protocol as-is, or does it require additional work to make the EVM work?

**Comment by Manav-Aggarwal** [comment]
Covered by ADR-009

**Comment by adlerjohn** [comment]
Does ADR-009 resolve this issue then @Manav-Aggarwal?
