### ISSUE TITLE
[Refactor]:  Update submitBlocksToDA for loop

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1602]
### Implementation ideas

REF: https://github.com/rollkit/rollkit/blob/bb27d2745397c94da1b2cb85f9c5a52af508cf34/block/manager.go#L889

I recommend that the for loop in `submitBlocksToDA` be update to remove the ctx from the loop condition with a select statement for better handling of the backoff sleeps. 

Currently
```go
for ctx.Err() == nil && !submittedAllBlocks && attempt < maxSubmitAttempts {
		res := m.dalc.SubmitBlocks(ctx, blocksToSubmit, maxBlobSize, gasPrice)
		switch res.Code {
		case da.StatusSuccess:
			// No sleep
		case da.StatusNotIncludedInBlock, da.StatusAlreadyInMempool:
			// calculate backoff
		case da.StatusTooBig:
			// sleep
		default:
			// sleep
		}
		attempt += 1
	}
```

This doesn't handle the context in a responsive way and also duplicates the sleep and backoff code. 

In stead we should have something like

```go
for !submittedAllBlocks && attempt < maxSubmitAttempts {
		res := m.dalc.SubmitBlocks(ctx, blocksToSubmit, maxBlobSize, gasPrice)
		switch res.Code {
		case da.StatusSuccess:
			...
		case da.StatusNotIncludedInBlock, da.StatusAlreadyInMempool:
			...
		case da.StatusTooBig:
			...
		default:
			...
		}
		if res.Code != da.StatusSuccess {
		        backoff = m.exponentialBackoff(backoff)
		}
		attempt += 1

		select {
		case <-ctx.Done():
		     break or return
		case <-time.After(backoff):
		}
}
```

**Comment by Teja2045** [comment]
Hi @MSevey, could you please review the PR and let me know if it looks good to you? If you have any suggestions or if there's anything you think we should add, I'm open to hearing your feedback. Thanks!

**Comment by MSevey** [comment]
@Teja2045 reviewed and left comments.
