### ISSUE TITLE
Privval for both aggregator and transaction keys

### ISSUE THREAD

**Issue by evan-forbes** [rollkit/rollkit#161]
Eventually, optimint will need to support private validator functionality in order to provide aggregators with the better opsec. Using the same privval package as tendermint is the obvious solution, but that will only work for aggregator keys, and optimint's privval will need to safe keep another key to sign celestia specific transactions. We will likely need to expand the functionality of tendermint's privval and perhaps even [tmkms](https://github.com/iqlusioninc/tmkms)

**Comment by evan-forbes** [comment]
iirc, there was no key in the light client at the time

This is also only important if the key is used for something important, otherwise the key in the lc is probably sufficient. For example, last time I checked sovereign was using the signature in the PFB tx as the signature for the block/header for the rollup. In that case, the key in the light client would likely not be sufficient.

**Comment by nashqueue** [comment]
Closing as we are using the key in the celestia light node to post transactions and that can be different from the seq key from genesis.
