### ISSUE TITLE
Testing issue: Error while dialing: dial tcp 127.0.0.1:7980: connect: connection refused

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#1642]
When I run tests with `make test` they pass.
Fun fact: when I call `go test -count 1 ./...` they fail, throwing multiple: `Error while dialing: dial tcp 127.0.0.1:7980: connect: connection refused`.
Running `go test -race -count 1 ./...` tests pass.

It seems that we need to start mock DA for `rpc/json` package tests.

**Comment by yarikbratashchuk** [comment]
can't reproduce, tests pass for me

**Comment by yarikbratashchuk** [comment]
on a second run got:
`--- FAIL: TestMockDAErrors (0.25s)
    --- FAIL: TestMockDAErrors/submit_timeout (0.25s)
        da_test.go:196:
            	Error Trace:	/root/rollkit/da/da_test.go:196
            	            				/root/rollkit/da/da_test.go:85
            	Error:      	"" does not contain "context deadline exceeded"
            	Test:       	TestMockDAErrors/submit_timeout
            	Messages:   	should return context timeout error`

**Comment by tzdybal** [comment]
What about running `go test ./rpc/...`?

**Comment by tzdybal** [comment]
We start mock DA server in `node_test.go` and `da_test.go`. But it is also used by `rpc/json` tests.
