### ISSUE TITLE
[EPIC] Production-ready EVM

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1723]
- [x] #1725
- [x] #1726
- [x] #1759 
- [x] #1594

**Comment by alanwilhelm** [comment]
This is fairly recent. Is Octane the way to go for a production EVM w/rollkit currently?

**Comment by Manav-Aggarwal** [comment]
@alanwilhelm both BeaconKit and OctaneEVM are the way to go for production EVM

**Comment by Manav-Aggarwal** [comment]
Closing this since we have Octane, Artela, BeaconKit in the docs now.
