### ISSUE TITLE
Revisit how DA gas fees estimation is done in Rollkit

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1727]
Building on top of https://github.com/celestiaorg/celestia-app/pull/3510, we should revisit how DA gas fees estimation is done in Rollkit

**Comment by tuxcanfly** [comment]
The linked PR seems to integrate Signer's `EstimateGas` method. I believe this does not affect rollkit in the default case where we allow node to estimate gas and fee @vgonkivs feel free to correct me.

**Comment by tuxcanfly** [comment]
Need to revisit this after https://github.com/celestiaorg/celestia-node/pull/3349 is merged.

**Comment by tuxcanfly** [comment]
Did not have an issue using default gas fees after celestia-node >= 0.13.7. Closing as fixed.
