### ISSUE TITLE
error: number of blocks pending DA submission (xxx + yyy) reached configured limit (xxx)

### ISSUE THREAD

**Issue by a26nine** [rollkit/rollkit#1788]
### Version of Git SHA

rollkit version:  `v0.13.5`
rollkit git sha:  `6a33192`

### System OS

Ubuntu 22.04

### Steps to reproduce it

- Find a rollup node that hasn't submitted blobs for a long time or was stuck due to some reasons
- Set `rollkit.max_pending_blocks` to a number less then the number of non-submitted blobs
- Restart rollup node daemon

### Expected result

The rollup node should post the pending blobs during the first batch and apply the limits later on. In this case, if the limits are applied from the first batch, the rollup is unable to progress and is stuck.

### Actual result

`ERR error while publishing block error="number of blocks pending DA submission (1875) reached configured limit (600)" module=BlockManager`

(in loop)

**Comment by tuxcanfly** [comment]
Tried to repro but seems to be fixed in celestia-node >= v0.13.7

See: https://github.com/celestiaorg/celestia-node/issues/3164#issuecomment-2163232709

**Comment by tuxcanfly** [comment]
This error indicates that the block creation is halted and will proceed once pending blocks are submitted. The error message can be improved, maybe something like:

>number of blocks pending DA submission (1875) reached configured limit (600), waiting to submit pending blocks first before creating new blocks

**Comment by a26nine** [comment]
> This error indicates that the block creation is halted and will proceed once pending blocks are submitted. The error message can be improved, maybe something like:
> 
> > number of blocks pending DA submission (1875) reached configured limit (600), waiting to submit pending blocks first before creating new blocks

Alright, that would be helpful. Thanks!

**Comment by a26nine** [comment]
Closing in favor of https://github.com/rollkit/rollkit/issues/1813.
