### ISSUE TITLE
Define Leader Selection for Cosmos-SDK based Rollup chain

### ISSUE THREAD

**Issue by liamsi** [rollkit/rollkit#18]
In a first version, we can live with one known aggregator node per ORU chain. Later, we want at least a committee of nodes to be aggregators. In the latter case, the pubkeys still can be known upfront by clients (and they should).

Later, ideally, we want that every node can be an aggregator node. In that case the pubkeys can't be known upfront and this case requires more thinking. 

We should also decide if we should implement this logic in the default execution environment (ref: #35) as opposed to (in golang) here or as an SDK module.

**Comment by liamsi** [comment]
I think @adlerjohn is best suited for this task.

**Comment by liamsi** [comment]
Ok, there has been no progress on this so far but it is also not really pressing as we can still first go with the centralized sequencer or aggregator approach (as it seems still most common in other rollup systems). 

Either way, here is a rough plan of how this could work is how I described a while ago in this discord post:
https://discord.com/channels/638338779505229824/804652273254268968/827205351925350421

The core idea is to use a similar weighted leader selection mechanism used in tendermint and a similar(but potentially simpler) bonding mechanism as in the staking module in the cosmos-sdk. 
For that, we could either modify the staking module or write a simpler "delegated bonding" or "leader-selection" module from scratch for this purpose. On the optimint side, the leader can be determined similarly as in tendermint: https://docs.tendermint.com/master/spec/consensus/proposer-selection.html

The difference to tendermint is that the (known) proposer will just submit the block to Celestia and that's it (while in tendermint the whole dance of rounds and proposal->prevote->precommit->commit would be started).

**Comment by Manav-Aggarwal** [comment]
Superseded by https://github.com/rollkit/rollkit/issues/815
