### ISSUE TITLE
[Feature Request]: Add a separate flag for mock DA server or improve conditional

### ISSUE THREAD

**Issue by a26nine** [rollkit/rollkit#1818]
### Implementation ideas

Looking at the code: https://github.com/rollkit/rollkit/blob/a95825f7ac1a1813acd3a7ced71aa838efa0cefb/cmd/rollkit/commands/run_node.go#L121-L129

It seems a mock DA server is initialised if the user doesn't pass a value with the `--rollkit.da_address` flag explicitly.

The default value for `--rollkit.da_address` is `http://localhost:26658` as seen here:
https://github.com/rollkit/rollkit/blob/a95825f7ac1a1813acd3a7ced71aa838efa0cefb/config/defaults.go#L30

(As in a real world situation) If the user is running a local light node with default config, it would run on `localhost` at port `26658`. So, it is expected that the rollkit rollup should connect to the local light node by default.

However, based on the conditional here:
https://github.com/rollkit/rollkit/blob/a95825f7ac1a1813acd3a7ced71aa838efa0cefb/cmd/rollkit/commands/run_node.go#L122

A mock DA server is initialised if the user doesn't pass a value with the `--rollkit.da_address` flag.  On the contrary, a mock DA server is not initialised if a value is passed that flag, even if it's the default value.

Meaning, to apply the default value and avoid creating a mock DA server, the user needs to explicitly pass `--rollkit.da_address http://localhost:26658`.

It's not good UX. Therefore, a couple of suggestions to improve it:
1. Add a flag to initiate or toggle a mock DA server, or,
2. Improve the conditional to check if a light node is running at the default address, and decide if the mock DA server needs to be created based on that.

**Comment by MSevey** [comment]
Thanks for submitting an issue!

Adding a flag for the mock DA I think creates the poor UX for the mock DA that you are experiencing for the DA light node. 

So I would recommend your second option to check if a DA node is already running on the default local host port.

**Comment by MSevey** [comment]
Did you get any sort of error with ports clashing when the mock DA was spun up on the same localhost port as your da light node?

**Comment by a26nine** [comment]
> Did you get any sort of error with ports clashing when the mock DA was spun up on the same localhost port as your da light node?

@jcstein encountered the error:
```
Error intercepting command:  Reading rollkit.toml: no rollkit.toml found
I[2024-08-26|18:20:15.562] Found private validator                      module=main keyFile=/Users/js/.rollkit/config/priv_validator_key.json stateFile=/Users/js/.rollkit/data/priv_validator_state.json
I[2024-08-26|18:20:15.562] Found node key                               module=main path=/Users/js/.rollkit/config/node_key.json
I[2024-08-26|18:20:15.562] Found genesis file                           module=main path=/Users/js/.rollkit/config/genesis.json
ERROR: failed to launch mock da server: listen tcp 127.0.0.1:26658: bind: address already in use
```

Discussion in the TG chat: https://t.me/rollkit/1659
