### ISSUE TITLE
[Feature Request]: add support for MultiAccounts on celestia-node

### ISSUE THREAD

**Issue by jcstein** [rollkit/rollkit#1821]
### Implementation ideas

Add DAKeyringKeyname flag to rollkit and update go-da to support this change, too

**Comment by tzdybal** [comment]
Is there a need to specify different account name per each `Submit` call? My intuition is that key name is rather static configuration option, and could be passed once, during initialization, not per call.

**Comment by jcstein** [comment]
During initialization would work. How do you pass it in in this case?

**Comment by jcstein** [comment]
So wouldn't it be set in initialization, then passed in every time Submit is used?

**Comment by tzdybal** [comment]
Resolved by #1852
