### ISSUE TITLE
Ecosystem example app

### ISSUE THREAD

**Issue by yarikbratashchuk** [rollkit/rollkit#1883]
### Implementation details

We need to build an app for rollkit stream on the 24th of October

App idea: "Prediction market on a prediction market"
    - **block enshrined oracle - election stuff.** get the odds at a certain time of day and make a market on top of the market. predict the odds in 5 minutes, will it increase or decrease? etc.
        - bet, amount, counterparty, resolver - https://x.com/js_horne/status/1842231959801471200
        - https://polymarket.com/event/presidential-election-winner-2024?tid=1728326886171
        - [[tmr.news](http://tmr.news/)](http://tmr.news)-like UI for submissions
        - use Skip’s oracle + Artela / Rollkit + Celestia

**Comment by Manav-Aggarwal** [comment]
Created https://github.com/yarikbratashchuk/market-prediction-app here
