### ISSUE TITLE
Ignite Apps Broken

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1886]
### Version of Git SHA

Rollkit v0.13.7

### System OS

MacOS

### Installed tools

Ignite v28.5.3

### Steps to reproduce it

Run through the wordle tutorial to build the app with ignite. The `ignite chain build && ignite rollkit init --local-da` step will fail. 

### Expected result

No failure

### Actual result

failed

### Relevant log output

```Shell
✘ Cannot build app:

error while running command go build -o /Users/matt/Code/go/bin/wordled -mod readonly -tags  -ldflags -X github.com/cosmos/cosmos-sdk/version.Name=Wordle -X github.com/cosmos/cosmos-sdk/version.AppName=wordled -X github.com/cosmos/cosmos-sdk/version.Version= -X github.com/cosmos/cosmos-sdk/version.Commit=6698e60d86540cbc4a0a559bd48f33a524e2481f -X github.com/cosmos/cosmos-sdk/version.BuildTags= -X wordle/cmd/wordled/cmd.ChainID=wordle .: # github.com/rollkit/rollkit/block
/Users/matt/Code/go/pkg/mod/github.com/rollkit/rollkit@v0.13.7/block/manager.go:988:14: assignment mismatch: 2 variables but ecdsa.SignCompact returns 1 value
: exit status 1
```

### Notes

I think this is related to how the cosmos-sdk-start and ignite are pulling rollkit `main` and not locked to a version. 

We need to do at least one of the following, if not both.
1. Figure out how to get ignite and the cosmos-sdk-start to lock to versions
2. fix the tutorial with the new sequencer work / header and block refactoring

## Update
`ignite chain build` executes without error on main which is good. The next release will resolve this issue. 

However I do then get these errors running the rollup against local da:

```
1:29PM INF Creating and publishing block height=1 module=BlockManager
1:29PM ERR error while publishing block error="failed to get transactions from batch: no batch to process" module=BlockManager
1:29PM INF starting API server... address=tcp://0.0.0.0:1317 module=api-server
1:29PM INF serve module=api-server msg="Starting RPC HTTP server on [::]:1317"
1:29PM INF starting gRPC server... address=localhost:9090 module=grpc-server
1:29PM ERR error while retrieving batch error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp [::1]:50051: connect: connection refused\"" module=BlockManager
1:29PM ERR error while retrieving batch error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp [::1]:50051: connect: connection refused\"" module=BlockManager
```

Steps to reproduce this are to following this guide: https://rollkit.dev/guides/ignite-rollkit#install-ignite-app-rollkit
After running `ignite rollkit add`, update rollkit and cosmos-sdk-starter to main with `go get`
```
go get github.com/rollkit/rollkit@main
go get github.com/rollkit/cosmos-sdk-starter@main
```
Then continue the tutorial steps.

**Comment by MSevey** [comment]
When following the how to guide (https://rollkit.dev/guides/ignite-rollkit) I get this error

```
gm % rollkit start --rollkit.aggregator --rollkit.da_address http://localhost:7980
docs/docs.go:16:12: pattern static: no matching files found
x/gm/module/autocli.go:6:2: package gm/api/gm/gm is not in std (/usr/local/Cellar/go/1.23.1/libexec/src/gm/api/gm/gm)
Error intercepting command:  failed to build entrypoint: exit status 1
```

**Comment by MSevey** [comment]
So the `ignite chain build` command is what is driving the error and that seems to be coming from the cosmos-sdk-start which is locked on rollkit v0.13.7.

**Comment by MSevey** [comment]
I think this is fixed on main: https://github.com/rollkit/rollkit/blob/fc65faf646a7cbec15dd9ff046648972f5edbb53/block/manager.go#L1217

Which means ignite is locked to a version, it just isn't clear how or where. 

It would seem via the cosmos-sdk-starter, but I can't seem to modify this via forks.

**Comment by MSevey** [comment]
I figured out how to test different versions. 

After running `ignite rollkit add` you can just run
```
go get github.com/rollkit/rollkit@main
go get github.com/rollkit/cosmos-sdk-starter@main
```

With the latest on main `ignite chain build` works as expected. 

However I do then get these errors running the rollup against local da:

```
1:29PM INF Creating and publishing block height=1 module=BlockManager
1:29PM ERR error while publishing block error="failed to get transactions from batch: no batch to process" module=BlockManager
1:29PM INF starting API server... address=tcp://0.0.0.0:1317 module=api-server
1:29PM INF serve module=api-server msg="Starting RPC HTTP server on [::]:1317"
1:29PM INF starting gRPC server... address=localhost:9090 module=grpc-server
1:29PM ERR error while retrieving batch error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp [::1]:50051: connect: connection refused\"" module=BlockManager
1:29PM ERR error while retrieving batch error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp [::1]:50051: connect: connection refused\"" module=BlockManager
```

**Comment by MSevey** [comment]
So the block get and publish errors seem to be due to the `--rollkit.aggregator` flag. 
When removed, the rollup starts just fine. 

@gupadhyaya is this expected? Or is this linked to the issue of the aggregator flag not being recognized @yarikbratashchuk

**Comment by MSevey** [comment]
Here are the updated steps to reproduce
```
ignite scaffold chain gm --address-prefix gm --minimal --skip-proto
cd gm
ignite app install github.com/ignite/apps/rollkit@rollkit/v0.2.1
ignite rollkit add
go get github.com/rollkit/rollkit@main
go get github.com/rollkit/cosmos-sdk-starter@main
go mod tidy
ignite chain build
ignite rollkit init
rollkit toml init
<rollkit start command>
```
Additionally having the local-da running via
```
cd $HOME && curl -sSL https://rollkit.dev/install-local-da.sh | sh -s v0.3.1
```

For the rollkit start command, i've seen the following errors.
```
rollkit start --rollkit.aggregator --rollkit.da_address http://localhost:7980
```
This causes the errors listed in the above comment and the top level issue description.

If you stop the rollup and re-run without the `aggregator` flag:
```
rollkit start --rollkit.da_address http://localhost:7980
```
This seems to work. 

However if you recreate the rollup, and then run that start command:
```
rollkit start --rollkit.da_address http://localhost:7980
```
You get the following errors
```
ERR failed to retrieve block from DALC daHeight=1 errors="failed to retrieve block: failed to get IDs: given height is from the future\nfailed to retrieve block: failed to get IDs: given height is from the future\nfailed to retrieve block: failed to get IDs: given height is from the future\nfailed to retrieve block: failed to get IDs: given height is from the future\nfailed to retrieve block: failed to get IDs: given height is from the future\nfailed to retrieve block: failed to get IDs: given height is from the future\nfailed to retrieve block: failed to get IDs: given height is from the future\nfailed to retrieve block: failed to get IDs: given height is from the future\nfailed to retrieve block: failed to get IDs: given height is from the future\nfailed to retrieve block: failed to get IDs: given height is from the future" module=BlockManager
```
Then if you try and restart, you get this errror
```
error while initializing BlockManager: genesis.InitialHeight (1) is greater than last stored state's LastBlockHeight (0)
Error intercepting command:  failed to run entrypoint: exit status 1
```

If you recreate the rollup and just run `rollkit start`, you get the following error:
```
error while initializing BlockManager: RPC client error: sendRequest failed: Post "http://localhost:26658": dial tcp [::1]:26658: connect: connection refused
Error intercepting command:  failed to run entrypoint: exit status 1
```

**Comment by MSevey** [comment]
Looking at the code more, it seems that the expected behavior is for the `rollkit start --rollkit.da_address http://localhost:7980` command to be used, since `rollkit start` is inheriting the `gmd start` command which does not spin up any dummy DA or dummy sequencer. 

So the missing piece it seems in the tutorial is for the sequencer local-da equivalent to be started and past in.

**Comment by MSevey** [comment]
If you run the centralized sequencer with the local-da, with the `rollkit start --rollkit.aggregator --rollkit.da_address http://localhost:7980` command you can successfully launch the rollup, but you see these logs

```
10:29AM INF Creating and publishing block height=1 module=BlockManager
10:29AM ERR error while publishing block error="failed to get transactions from batch: no batch to process" module=BlockManager
10:29AM ERR error while retrieving batch error="rpc error: code = Unknown desc = invalid rollup id" module=BlockManager
```

Then on restart you get the following error
```
error while initializing BlockManager: genesis.InitialHeight (1) is greater than last stored state's LastBlockHeight (0)
Error intercepting command:  failed to run entrypoint: exit status 1
```

**Comment by gupadhyaya** [comment]
@MSevey cleaning the rollkit data directory and restarting rollkit app should fix the above issue.

**Comment by MSevey** [comment]
> @MSevey cleaning the rollkit data directory and restarting rollkit app should fix the above issue.

@gupadhyaya ok but what about the original issue of the errors on starting?

**Comment by gupadhyaya** [comment]
you mean: `/Users/matt/Code/go/pkg/mod/github.com/rollkit/rollkit@v0.13.7/block/manager.go:988:14: assignment mismatch: 2 variables but ecdsa.SignCompact returns 1 value`? 
it should go away with next release
