### ISSUE TITLE
Dockerize EVM Rollup with BeaconKit

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1895]
Relevant link: https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/2

**Comment by Manav-Aggarwal** [comment]
Waiting on Callum's feedback

**Comment by tuxcanfly** [comment]
This has been implemented here, thanks @cmwaters  : https://github.com/celestiaorg/celestia-zkevm-ibc-demo/blob/7b6ba45013272f0347b3dc3a983cac076b780faa/docker-compose.yml#L3
