### ISSUE TITLE
Maintain correct block time after restarting

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#195]
[Current implementation of `AggregationLoop`](https://github.com/celestiaorg/optimint/blob/main/block/manager.go#L128) produce a block as soon as it starts. This ensures that when starting a chain, genesis will be generated ASAP.

In case the app is restarted, next block will be produced immediately. This is not desirable (as aggregator can restart node faster than block time).

First produced block should use block time and time of last block creation to calculate the wait before producing a block.

**Comment by toanngosy** [comment]
Assign me this @tzdybal

**Comment by toanngosy** [comment]
Reference to #278
