### ISSUE TITLE
Multi-aggregator mode

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#204]
Multi-aggregator mode means that Optimint network can contain more than one aggregator (block producer).

There are two main areas of required development:

- [ ] #507
   - [x] #205
   - [x] #206
   - [x] #207
- [ ] #508
   - [x] #208
   - [x] #209
   - [x] #210
   - [x] #211
   - [x] #479 
   - [x] #484

**Comment by adlerjohn** [comment]
My recommendation is to start with native leader selection+staking through the Cosmos SDK staking app, since it involves much less work I think.

**Comment by tzdybal** [comment]
Another idea related to multi-aggregator operation, kind of "free for all" mode:
 - allow anyone to create blocks
 - use block ordering directly from Celestia, ignore block heights in optimint headers

**Comment by adlerjohn** [comment]
Thought dump: would also be nice if there was a DAG mode, where new "blocks" can be appended on top of any other block instead of just the latest.

**Comment by Manav-Aggarwal** [comment]
Closing since decentralized sequencers aren't a priority.
