### ISSUE TITLE
Block explorer for Rollkit Rollups

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#213]

**Comment by liamsi** [comment]
IMO, this could also be based on a cosmos block explorer if there is full RPC compatibility. big dipper 2 uses a postgres db: https://github.com/forbole/big-dipper-2.0-cosmos

But maybe it's worth trying to stick to the old big dipper here. But that is one action item to decide which block explorer to use / modify here.

**Comment by Manav-Aggarwal** [comment]
Closing since not relevant anymore
