### ISSUE TITLE
High-level architecture specification 

### ISSUE THREAD

**Issue by liamsi** [rollkit/rollkit#23]
[This document](https://docs.google.com/document/d/12gZow_JTJjRrmaD2mNTmYniLhyxVLSyDd7Fbxo5UnA8/edit) together with the issues in this repository represent the closest thing to a specification of the Cosmos SDK optimistic rollup execution environment.

It would be good, if:
 
1. we created ADRs for all larger impact decisions made in this repository
2. we extract/compile some high-level specification / documentation from this later.

This issues is mostly about the second point. For this, we can likely re-use the above-mentioned document and quite often we can simply refer to the Cosmos-SDK docs.  One option could be to maintain that document. On the long run, it would be favourable if a markdown version of its contents would be part of the repository instead.

**Comment by Manav-Aggarwal** [comment]
> On the long run, it would be favourable if a markdown version of its contents would be part of the repository instead.

Markdown version part of repository: https://github.com/rollkit/rollkit/tree/main/specs/src/specs
