### ISSUE TITLE
Develop a testing strategy

### ISSUE THREAD

**Issue by liamsi** [rollkit/rollkit#24]
Ideally, the following tests should exist:

 1. reasonably high test coverage via unit-tests inside this repo 
 1. integration tests between lazyledger-app and optimint
 1. run the simapp with optimint (see https://docs.cosmos.network/master/building-modules/simulator.html and https://github.com/cosmos/cosmos-sdk/blob/deaee531111fb4aad3ccabbfa6771f9a67ae42ce/simapp/app.go#L1)
 1. integration tests between lazyledger-app and another very simple ORU app based on the Cosmos-SDK (using optimint under the hood)
 1. spin up a small network with the LL main chain and two simple apps with their own dedicated clients 

The first point is the only one that we needs immediate and continuous action. And I think we are on the right track for this. For the other points it is a bit too early but we should have them before the first testnet with ORU support.

We should definetely split this up into several issues. Point 5. alone is a bigger project on its own. I just wanted to jot this down for now. We could use this issue as a kind of meta issue to link between all relevant issues (and prs).

**Comment by Manav-Aggarwal** [comment]
Closing this since testing has been added extensively to Rollkit
