### ISSUE TITLE
Create ADR describing the leader selection in details

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#247]
* We need to make the staking module fraud provable
* General single round fraud proofs using microblocks
* Tendermint (validator priority) style leadership selection 
  * The leadership selection rule doesn’t have to be fraud provable, but it does have to be runnable by light clients
  * The light clients could also rely on a committee to sign over valid blocks instead of running the leadership selection rule themselves (see #220)

**Comment by Manav-Aggarwal** [comment]
Closing since decentralized sequencers aren't a priority.
