### ISSUE TITLE
Adopt Tendermint style validator priority logic for leader selection

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#250]

**Comment by liamsi** [comment]
Context: 
- https://docs.tendermint.com/master/spec/consensus/proposer-selection.html
- https://github.com/tendermint/tendermint/blob/3c8955e4b824b1dcec7176832b2d5d96dad9fcad/types/validator_set.go#L116

**Comment by Manav-Aggarwal** [comment]
Covered by https://github.com/rollkit/rollkit/issues/815
