### ISSUE TITLE
Implement proper ConsensusParams handling

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#291]
Consensus params can be changed with regards to ABCI during `EndBlock`.  This logic is not yet ready.

Updates may be processed in a similar way as validator set updates, in [`updateState method`](https://github.com/celestiaorg/optimint/blob/main/state/executor.go#L166).

**Comment by Manav-Aggarwal** [comment]
Handled in https://github.com/rollkit/rollkit/pull/1367
