### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#317]
Readme should contains at least:
 - more information about the project in general
 - information what the currently implemented functionality - what a user can expect
 - information on "how to use" optimint
 - information about contributing (see: #140)

**Comment by mauriceLC92** [comment]
Does a write-up exist for "how to use" Optimint? I would like to read something like that if possible :) I do not mind taking it from rough form and turning it into the section for the README. I think I need something like that if I want to contribute on deeper issues

**Comment by tzdybal** [comment]
Unfortunately it doesn't exist. TBH my plan is to write a blog post about spinning up optimint network and link it, but first I would like to have multi-aggregator mode working.

**Comment by nashqueue** [comment]
Closed by #942
