### ISSUE TITLE
Implement `HeaderByHash` RPC method

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#356]
New Tendermint release introduced `HeaderByHash` method. It needs to be implemented. 

https://github.com/celestiaorg/optimint/blob/tzdybal/latest-cosmos/rpc/client/client.go#L402

Blocked by: #350

**Comment by nashqueue** [comment]
This method is already implemented.  https://github.com/rollkit/rollkit/blob/dc0516db39e23799de983c85a1c89d15209a132b/node/full_client.go#L805C24-L805C24
