### ISSUE TITLE
Implement `RemoveTx` RPC method

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#357]
New Tendermint release introduced `RemoveTx` method. It needs to be implemented. 

https://github.com/celestiaorg/optimint/blob/tzdybal/latest-cosmos/rpc/client/client.go#L554

Blocked by: #350

**Comment by allanperlee** [comment]
Hi tzdybal, I am interested in implementing solutions for these RPC issues. Is it still blocked by #350?

**Comment by tzdybal** [comment]
Hey @allanperlee! Currently we can't merge #350, because of dependencies. But you can work on this, just start by branching from `tzdybal/latest-cosmos`, and create PR with this branch as a target. This way your changes will find a way into `main` eventually.

**Comment by allanperlee** [comment]
Excellent, thanks for assigning this to me. This RPC method should invoke a `c.type` method correct? I referred to the import for `ctypes "github.com/tendermint/tendermint/rpc/coretypes"` but it is nonexistent. Is there another go file with this type that can be used for reference?

**Comment by tzdybal** [comment]
This method should probably invoke `RemoveTxByKey` on mempool.

**Comment by nashqueue** [comment]
This method does not exist in 37+ anymore.
