### ISSUE TITLE
Minimize Tendermint dependencies

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#37]
Because Optimint is a "drop-in replacement" of Tendermint, we should minimize dependencies on Tendermint (lazyledger-core) packages.

All dependencies cannot be eliminated, because structs/interfaces are used in common API.

Easiest way of eliminating dependencies is to copy code into optimint repository.

**Comment by liamsi** [comment]
is this still relevant?

**Comment by tzdybal** [comment]
Not sure TBH. Probably we should re-assess this.

**Comment by tzdybal** [comment]
Issues:
1. `types` are everywhere ;) There are `github.com/tendermint/tendermint/abci/types` (generated from protobuf), `github.com/tendermint/tendermint/types` (hand crafted, with extra functionalities), `github.com/tendermint/tendermint/proto/...` (generated from protobuf). In many places they are mixed (`tendermint/tendermint/types` use `tendermint/tendermint/proto/types`, etc).
1. All the types are `struct`s, not `interface`s - it's hard to substitute types.
1. Optimint is connected to cosmos-sdk app as a library, any many arguments use types from `github.com/tendermint/tendermint`. There's no extra protobuf serialization, to let us use "same" types (copied/regenerated).
1. Optimint still use some "hand crafted" types to access extra logic.

**Comment by tzdybal** [comment]
_OMG, I just found pre-historic browser tab with following comment that was not submitted for many months :facepalm:_

Issues:
1. `types` are everywhere ;) There are `github.com/tendermint/tendermint/abci/types` (generated from protobuf), `github.com/tendermint/tendermint/types` (hand crafted, with extra functionalities), `github.com/tendermint/tendermint/proto/...` (generated from protobuf). In many places they are mixed (`tendermint/tendermint/types` use `tendermint/tendermint/proto/types`, etc).
1. All the types are `struct`s, not `interface`s - it's hard to substitute types.
1. Optimint is connected to cosmos-sdk app as a library, any many arguments use types from `github.com/tendermint/tendermint`. There's no extra protobuf serialization, to let us use "same" types (copied/regenerated).
1. Optimint still use some "hand crafted" types to access extra logic.

**Comment by nashqueue** [comment]
Can be closed in favor of #1125
