### ISSUE TITLE
Add support for multiple nodes in DA layer connection

### ISSUE THREAD

**Issue by jbowen93** [rollkit/rollkit#456]
Sometimes a specific `celestia-node` bridge node may be unable to submit blocks, usually because of current peering issues in `celestia-app`. The existing Optimint config only supports a single BaseURL which is used to [create a client](https://github.com/celestiaorg/optimint/blob/main/da/celestia/celestia.go#L50). 
```
type Config struct {
	BaseURL     string        `json:"base_url"`
	Timeout     time.Duration `json:"timeout"`
	GasLimit    uint64        `json:"gas_limit"`
	NamespaceID [8]byte       `json:"namespace_id"`
}
```

We should support passing in an array of `BaseURLs` and creating multiple clients. Failed calls should result in retry logic that cycles through different clients.

**Comment by Manav-Aggarwal** [comment]
Closing this since it's not relevant anymore.
