### ISSUE TITLE
Switch to immediate execution

### ISSUE THREAD

**Issue by liamsi** [rollkit/rollkit#488]
The apphash / state root in the header should reflect the state of the Txs included in the corresponding block (of same height). This should be a simple change in optimint as it does not require any changes to consensus (as there is none). 

> Not having immediate execution potentially adds a lot of complexity for fraud/zk proofs

This should be documented in an ADR and also there should be a disclaimer that this actually breaks compatibility with (at least some modules) in the cosmos-sdk (to be confirmed and documented as well).

Also, as part of this someone should look into the implications on the SDK side! And potenially write a (very simple) module that e.g. replaces the staking module (which most likely assumes deferred execution). 

This will most likely also impact the default IBC implementation (see https://github.com/celestiaorg/optimint/issues/220).

 - [ ] document decision and impact in ADR
 - [ ] look into potential caveats related to either ABCI or existing SDK modules (IBC, staking etc)
 - [ ] implement and test with etheremint, wordle and other apps

**Comment by Manav-Aggarwal** [comment]
Closing this since it's not clear when this will be relevant again.
