### ISSUE TITLE
Random namespace ID for development

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#491]
To ease up development, there should be option to generate random namespace id by optimint. We can see, that currently developers often use the same namespace ID, which leads to errors and confusion.

Of course, once generated ID needs to be saved for further runs (this will be done in configuration).

Related and probably blocked by #425.

**Comment by tzdybal** [comment]
This is more complicated than I expected. We probably need some changes in cosmos-sdk to enable automatic "save" into config file.

**Comment by Manav-Aggarwal** [comment]
[Local-DA](https://github.com/rollkit/local-da) is now used for any local rollup development now, so needing random namespaces is unindeed. Please feel free to reopen if things change.
