### ISSUE TITLE
Define aggregator 

### ISSUE THREAD

**Issue by liamsi** [rollkit/rollkit#50]
Define the aggregator in an ADR ideally accompanying a draft implementation.

Aggregators are full nodes that aggregate and "propose" a block by submitting it to the DA layer. 

We've talked extensively about how this could look from an implementation point of view but never wrote this down in detail anywhere. Essentially, the aggregator takes a bunch of transactions from the mempool, creates a block out of those, and submits the block as a PayForMessage with the namespace of the ORU to the Data Availability layer. 

ref: #18

**Comment by Manav-Aggarwal** [comment]
Refer to https://rollkit.github.io/rollkit/specs/block-manager.html#block-production
