### ISSUE TITLE
Sequencerless pessimistic mode

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#509]
And now, for something completely different: instead of publishing blocks in the DA layer, Optimint can should be able to use DA layer as inbox for transactions. In this context _pessimistic_ means - there are no light clients, everyone is executing all transactions.

1. Everyone is allowed to submit transactions directly to DA layer.
1. Every node reads transactions from DA layer and feeds them into mempool.
1. P2P communication between nodes is not required (with some assumptions).

----

What needs to be done?
- [ ] #510
- [ ] #511
- [ ] #512

**Comment by Manav-Aggarwal** [comment]
This is simply a based rollup mode that will be supported post #1649
