### ISSUE TITLE
Define Block sync

### ISSUE THREAD

**Issue by liamsi** [rollkit/rollkit#51]
With block sync we mean the protocol for full-nodes that join the network later but want to download all their OUR chain's block data from genesis.

1. [ ] Discuss different design approaches here and capture the discussion and the decision in an ADR.
2. [ ] Implement the described decision above.

Both steps could happen in parallel, or a draft implementation could even lead the discussion (it should be easy to again leverage the same approach as in #48 but parallelize it heavily s.t. it is feasible to sync even after the chain has been running for quite a while).

**Comment by Wondertan** [comment]
- Do the end clients meant to share transactions with each other or they only receive them from aggregators once the block is committed?

- What do you think about having two protocols for block data fetching? From any LL node and from the node who is the same ORU.

**Comment by liamsi** [comment]
> Do the end clients meant to share transactions with each other or they only receive them from aggregators once the block is committed?

Not sure what you mean by end clients but ORU full-nodes will gossip transactions too. Not all of them have to be aggregators necessarily.

> What do you think about having two protocols for block data fetching? From any LL node and from the node that is the same ORU.

Not really sure. We can't do without the LL one, and we could potentially do without the protocol amongst the same ORU nodes. The additional protocol between ORU nodes could be more efficient, but I think headers should still be downloaded from the DA layer.
