### ISSUE TITLE
End to End Testing

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#518]
We need to establish E2E testing infrastructure to be more confident about integration of all components required to run a rollup (celestia-app, celestia-node, optimint enabled cosmos-sdk). Ideally those tests should be integrated into celestia-node testing environment. 

Ideas for test scenarios:
1. Happy path 
   1. aggregator posts blocks to DA
   1. full nodes are able to sync
   1. transactions are submitted from all nodes
1. full-nodes
   1. syncing from scratch - catching up
   1. starting full node before aggregator and staying in sync
   1. restart during catch up
   1. restart when being in sync   
1. light nodes - TBD
1. fraud proofs
   1. generation
   1. gossiping / propagation
   1. verification
   1. fraudulent fraud proof
   1. fraud in BeginBlock
   1. fraud in EndBlock
   1. fraud in first transaction in the block
   1. fraud in last transaction in the block
   1. fraud in transaction in the middle of the block
1. Other
   1. chain update

**Comment by Manav-Aggarwal** [comment]
Closing in favor of other testing related issues.
