### ISSUE TITLE
Gossip Fraud Proofs to P2P network after generation when needed

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#552]
Currently, a fraud proof is not gossiped after it is generated by the state executor. We'd like to add this usage and use the capability added in this [PR](https://github.com/celestiaorg/rollmint/pull/452)

**Comment by randomshinichi** [comment]
I'd be interested in doing this!

**Comment by tzdybal** [comment]
Hey, sorry for a little bit of confusion (issue wasn't assigned), but @Manav-Aggarwal will work on this.
