### ISSUE TITLE
Create new base-app instead of setting it in existing base-app

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#572]
A rollmint light client does not start with a Cosmos-SDK app. In `server/start.go`, there is a notion of an `appCreator` which is how a cosmos-sdk app is initially initialized. We'd like to combine `SetupBaseAppFromFraudProof` described in the fraudproof prototype [here](https://github.com/celestiaorg/cosmos-sdk-rollmint/blob/cdcddca470a11a5542193673cf9c59ebd5516f76/baseapp/baseapp.go#L936) with this `appCreator`.

After this is done, a rollmint light client should be able to spin up a new Cosmos SDK app and initialize its store with Deep Subtrees constructed using merkle inclusion proofs in the `FraudProof`. After this initialization, the app hash representing the state of the app should match the `appHash` inside the `FraudProof`. Also, this store should now contain all the key/value pairs and underlying tree structure necessary to execute the fraudulent state transition contained in the `FraudProof`. 

This issue should also resolve this comment: https://github.com/celestiaorg/cosmos-sdk-rollmint/pull/1/files#r997083032

**Comment by Manav-Aggarwal** [comment]
https://github.com/rollkit/rollkit/issues/1632#issuecomment-2408212822
