### ISSUE TITLE
Move Stage 2 & 3 of Fraud Proof Verification from cosmos-sdk to Rollkit

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#573]
Currently, stage 2 & 3 of Fraud Proof Verification described [here](https://github.com/celestiaorg/rollmint/blob/manav/state_fraud_proofs_adr/docs/lazy-adr/adr-009-state-fraud-proofs.md) live in the cosmos-sdk fraudproof prototype [here](https://github.com/celestiaorg/cosmos-sdk-rollmint/blob/7db91316a32cc09b2b472837b634950666621df3/baseapp/fraudproof.go#L98).

We'd like to move these stages of verification into Rollmint instead since it takes place before a new cosmos-sdk app gets spun up by a rollmint light client which is a relatively expensive operation.

It requires some proof libraries that live in cosmos-sdk currently and we'd need to figure out a way to use the same libraries in Rollmint.

**Comment by Manav-Aggarwal** [comment]
https://github.com/rollkit/rollkit/issues/1632#issuecomment-2408212822
