### ISSUE TITLE
Implement `Data.ValidateBasic`

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#626]
Currently there is no validation in `ValidateBasic` method of block `Data`.
https://github.com/celestiaorg/rollmint/blob/3a518be702b3d4183deb888fbc7958fcc2c3b2bc/types/validation.go#L38-L42

Methods should check:
- [ ] Number of ISRs corresponds to number of TXs
- [ ] ISR's are valid hashes (length is OK)

**Comment by Manav-Aggarwal** [comment]
Related: https://github.com/rollkit/rollkit/issues/1271

**Comment by Manav-Aggarwal** [comment]
Duplicate of https://github.com/rollkit/rollkit/issues/1271
