### ISSUE TITLE
Invalid Formatting Proofs

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#628]
If sequencer produce block that couldn't be validated (with `Block.ValidateBasic`) and signs it, full nodes should produce proof of this misbehavior.
For example, sequencer can publish a block without ISRs, or with missing ISRs. 

Ref: https://github.com/celestiaorg/rollmint/pull/570#issuecomment-1320309957

**Comment by Manav-Aggarwal** [comment]
No concept of ISRs anymore: https://github.com/rollkit/rollkit/issues/1632#issuecomment-2408212822
