### ISSUE TITLE
Limit fraud proofs size

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#629]
> there should be some consideration to fraud proofs for when a fraud proof contains more state witnesses than is permissible - eg the application (and fraud proof) has a limit to how much state keys each transaction can access.

_Originally posted by @musalbas in https://github.com/celestiaorg/rollmint/issues/570#issuecomment-1320309957_

**Comment by Manav-Aggarwal** [comment]
https://github.com/rollkit/rollkit/issues/1632#issuecomment-2408212822
