### ISSUE TITLE
`TestGossiping` is flaky

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#630]
`TestGossiping` (in p2p package) is flaky. 

Failed test execution: https://github.com/celestiaorg/rollmint/actions/runs/3536239910/jobs/5935086939

Possible cause of error: Context used by the test is canceled in `defer` statement, and some goroutines are still running after the test function returns.

Possible solution: cancel context earlier; give some time to stop the goroutines (`Sleep`?)

**Comment by Manav-Aggarwal** [comment]
Investigated this, I ran this test locally multiple times using:

`go test -v -run=TestGossiping -count=30 ./p2p`

and it is not flaky anymore. My best guess is https://github.com/rollkit/rollkit/pull/1434 which was resulted in resolving most flaky tests also ended up fixing this issue.
