### ISSUE TITLE
Log namespace id when the node is starting

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#653]
It would be useful (mostly for debugging) to print namespace id to logs when app is starting.

**Comment by ef3n9r98** [comment]
Hi @tzdybal, if you're not working on this issue yourself, I know some devs who would be. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by S1nus** [comment]
Consider keeping a field in the genesis for the daStartHeight, and write it to the file as soon as it becomes known.
this is because daStartHeight defines the rollup, and it makes sense to put it along with the rest of that info.
