### ISSUE TITLE
GM CI

### ISSUE THREAD

**Issue by jcstein** [rollkit/rollkit#677]
# gm CI

- I spoke briefly with @nashqueue regarding new Github Action for rollkit using gm and a fix for Ethermint CI
- the GM script/CI would be something like:
    1. install golang, ignite cli
    2. run ephemeral cluster, look into @mojtaba-esk's https://github.com/mojtaba-esk/celestia-local, either script or in yaml
    4. light node running that is funded with test tokens
    5. seems a little tricky to test in CI *unless* on an **ephemeral cluster**
    6. scaffold the chain
    7. cd to chain directory
    8. install rollmint
    9. scaffold a query
    10. modify the `gm/x/gm/keeper/grpc_query_gm.go` file to return a response on query
    11. start the sovereign rollup (by cloning the script in devrel tools)
    12. run [init.sh](http://init.sh/) script
    13. open a new terminal instance to test the query to confirm chain is alive
    14. look for confirmation on the rollkit output to look for `INF commit synced commit=`

**Comment by nashqueue** [comment]
Moved Ethermint Issue into a separate issue , because they can be addressed separately.

**Comment by jcstein** [comment]
edited title ✅

**Comment by MSevey** [comment]
Is this a new Workflow or updating an existing one?

If existing, can you link to the file so we know which one we are looking at?

**Comment by jcstein** [comment]
new, it would be similar to the Ethermint CI. if we can fix Ethermint CI, i don't know that it's 100% necessary, but GM CI may be useful

**Comment by nashqueue** [comment]
Relating to this, here is a new proposal after conversations with @tzdybal : 

Create a docker image, from stable and official core + node docker images. This will be in contrast to the manual config creation that needs to happen in the ephermal-cluster. This can be heavily inspired by the integration tests of [go-cnc](https://github.com/celestiaorg/go-cnc/tree/main/integration_test/docker). 

With this minimal setup running, we will run a gm-script on top of that (and any other tutorial). Regarding the testing of CLI input/outputs, we can use https://github.com/bats-core/bats-core **inside** the gm-script. 

The minimal Celestia setup generation will be on its own repo. 
The scripts of the tutorials will live in the documentation repo. 

The GitHub action of the rollkit commits will pull the image from one repo and the tutorials from the other.

**Comment by jcstein** [comment]
https://www.loom.com/share/670fa7d7092749749b797260675f50c4

https://www.loom.com/share/670fa7d7092749749b797260675f50c4

**Comment by nashqueue** [comment]
Do you want to add tests with the bats repo I linked above?

**Comment by jcstein** [comment]
Yes, need to do that to check for `INF commit synced commit=`

**Comment by jcstein** [comment]
Updated script for new versions and moved repo: https://github.com/jcstein/devrel-tools/blob/main/gm/gm-ci.sh

**Comment by jcstein** [comment]
i'm reopening this. not sure why it was closed

**Comment by jcstein** [comment]
I think I will need the devops team to take this over so it can be prioritized

**Comment by smuu** [comment]
DevOps epic: https://github.com/celestiaorg/devops/issues/116

**Comment by Manav-Aggarwal** [comment]
Close this after this is in a cosmos-sdk branch.

**Comment by Manav-Aggarwal** [comment]
Closing as stale issue.
