### ISSUE TITLE
Ethermint CI

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#678]
This issue was moved from #677 into a separate issue by @jcstein 
- for a fix on current Ethermint CI
    - for example on this PR: [https://github.com/celestiaorg/rollmint/pull/646](https://github.com/celestiaorg/rollmint/pull/646)
    - 2 potential solutions
    - 1. my initial guess for these errors `docker-build-ethermint-debug / docker-build (pull_request) Failing after 7m` and `docker-build-test-ethermint / docker-build (pull_request) Failing after 6m` is that it isn’t following the same format as this bit here: [https://docs.celestia.org/developers/rollmint-on-ethermint#ethermintd-installation](https://docs.celestia.org/developers/rollmint-on-ethermint#ethermintd-installation) -> could be added here: [https://github.com/celestiaorg/rollmint/actions/runs/3830996037/workflow#L38](https://github.com/celestiaorg/rollmint/actions/runs/3830996037/workflow#L38)
    - 2. looking at dockerfile in ethermint repo, this also could be where the fix belongs: dockerfile: [https://github.com/celestiaorg/ethermint/blob/main/docker/Dockerfile](https://github.com/celestiaorg/ethermint/blob/main/docker/Dockerfile)

**Comment by jcstein** [comment]
I think this also needs to be reopened?
