### ISSUE TITLE
Decide on type of height related fields

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#688]
Original implementation used `uint64` to represent any type of `height`. This seems to be the most appropriate type.
The convention in Tendermint/Cosmos-SDK is to use `int64`. The same for `go-header` library.

We need to decide what type should be used and change the code accordingly.

**Comment by Wondertan** [comment]
Note that go-header’s int usage is not a requirement, and we can change it if needed.

**Comment by Manav-Aggarwal** [comment]
Duplicate of https://github.com/rollkit/rollkit/issues/1176
