### ISSUE TITLE
`InitialBlockHeight` is handled incorrectly

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#699]
In `publishBlock` block number is always retrieved from store, and `InitialBlockHeight` from genesis is ignored. But the, few lines below height is actually compared to `InitialBlockHeight`, which makes no sense.

https://github.com/celestiaorg/rollmint/blob/008281cfd6e668e85e287cd7dcd4cbb6d3aea746/block/manager.go#L427-L433

We should make sure that `InitialBlockHeight` from genesis is properly used for first block.

**Comment by Manav-Aggarwal** [comment]
Duplicate of https://github.com/rollkit/rollkit/issues/1360
