### ISSUE TITLE
Rollback of invalidated transactions

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#7]
After receiving and validating fraud proof, node needs to rollback all blocks and transactions following block referenced in fraud proof.

It's app-layer responsibility to resend transactions.

**Comment by tzdybal** [comment]
Should we also invalidate all pending transactions from mempool?

**Comment by liamsi** [comment]
Again, the focus for testnet can be the evm settlement hub. It could also just be a nice-to-have because nodes can just run fullnodes at testnet.

**Comment by Manav-Aggarwal** [comment]
Not needed since we resort to social consensus for rollbacks
