### ISSUE TITLE
New syncing Light Clients will not get notified by FraudProof

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#700]
If a new light client joins the Network and tries to sync, it will not get notified if a fraud-proof happened in the past. 

This is because of 2 things: 
- Full Nodes halt after Fraudproof and disappear
- Full Nodes do not save FraudProofs of previous blocks

A thing we could consider is the full nodes staying and saving the fraudproof for other nodes. 
Another thing that could be interesting is to write a fraudproof module for the cosmos-sdk so we can put the fraudproof inside the block and automate the process so the network does not need to halt.  This will require further investigation.

**Comment by Manav-Aggarwal** [comment]
@nashqueue
