### ISSUE TITLE
Create `ErrApplyBlock` with `Unwrap` method.

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#707]
Create `ErrApplyBlock` with `Unwrap` method.

_Originally posted by @tzdybal in https://github.com/rollkit/rollkit/pull/643#discussion_r1084904965_

**Comment by raadhshenshahhaseeb** [comment]
@tzdybal Hi, if this issue is still open, can I work in it?

**Comment by Manav-Aggarwal** [comment]
https://github.com/rollkit/rollkit/issues/1632#issuecomment-2408212822

**Comment by Manav-Aggarwal** [comment]
https://github.com/rollkit/rollkit/issues/1632#issuecomment-2408212822
