### ISSUE TITLE
Soft Confirmations for Centralized Sequencers

### ISSUE THREAD

**Issue by S1nus** [rollkit/rollkit#712]
**Goal**
Improve the UX of roll-ups with centralized sequencers by having them build and publish blocks faster than the Celestia blocktime and respond to transactions with the block they're included in.

One way to do it is:
1. when it receives a transaction request:
  - start building a block
  - include any transactions that arrive in the next ~3 seconds in that block
  - respond to the request with that block
  - publish it over gossip (or simply expose it over RPC) and send to DA layer

**Comment by nashqueue** [comment]
Why do we close it as completed? Which issue implemented this? If it is not completed it should be closed as not planned.
