### ISSUE TITLE
Odd error when submitting Rollkit blocks

### ISSUE THREAD

**Issue by jcstein** [rollkit/rollkit#728]
I (and some of our ecosystem projects) have been getting this error on each Rollkit DA block submission: `5:52PM INF submitting block to DA layer height="marshaling error: json: unsupported type: func() int64" module=BlockManager`

**Comment by tzdybal** [comment]
This is an error in logger only. It's already fixed by #723, but it's not released yet.

**Comment by jcstein** [comment]
thank you, passed on to those who reached out!
