### ISSUE TITLE
Used quic-go version (v0.31.1) is not supported with the use of Go 1.20

### ISSUE THREAD

**Issue by smuu** [rollkit/rollkit#729]
Used quic-go version (v0.31.1) is not supported with the use of Go 1.20

See the explanation here: https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions

v0.32.0 has support for Go 1.20: https://github.com/quic-go/quic-go/releases/tag/v0.32.0

**Comment by Manav-Aggarwal** [comment]
Covered by https://github.com/rollkit/rollkit/pull/1155
