### ISSUE TITLE
Regenerate protobuf types script fails

### ISSUE THREAD

**Issue by smuu** [rollkit/rollkit#730]
When running:

```shell
./proto/gen.sh
```

I get the following error:

```
proto/tendermint/abci/types.proto:8:8:tendermint/crypto/proof.proto: does not exist
cp: cannot stat './proto/pb/*': No such file or directory
```

I don't know what causes this, but I was running the `go build` before I tried to run that script.

**Comment by tzdybal** [comment]
You need to call `./proto/get_deps.sh` first. You'll need to call this scripts only if you have changed proto files - no need for normal builds.

**Comment by nashqueue** [comment]
With a clean slate, you will need to call `./proto/get_deps.sh` as well. I had the same issue but did not change the proto files. We should add it to the readme
