### ISSUE TITLE
Merge header gossip with header exachange

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#735]
After https://github.com/rollkit/rollkit/pull/684 is merged, there will be two header gossips and we need to merge them. Preferably just use the header exchange gossip.

**Comment by tzdybal** [comment]
Latest commit is gossiped along with latest header, to enable multiple-sequencer scenario. Without this, active sequencer will produce a block, but other full nodes / sequencers won't be able to sync it - they will lag one block behind active sequencer.

I totally agree that the commit is not required by light nodes, so they shouldn't receive it. I think that separate gossiping of only commits make sense, and this gives us extra granularity, so full nodes (especially decentralized sequencers in the future) can subscribe, and other nodes can avoid overhead.

**Comment by gupadhyaya** [comment]
> Latest commit is gossiped along with latest header, to enable multiple-sequencer scenario. Without this, active sequencer will produce a block, but other full nodes / sequencers won't be able to sync it - they will lag one block behind active sequencer.
> 
> I totally agree that the commit is not required by light nodes, so they shouldn't receive it. I think that separate gossiping of only commits make sense, and this gives us extra granularity, so full nodes (especially decentralized sequencers in the future) can subscribe, and other nodes can avoid overhead.

with the addition of header exchange service, all nodes will be able to receive and sync to latest state. they dont need signed header. will it not suffice? right now, we have syncer disabled for sequencer nodes. but we can enable it.

**Comment by tzdybal** [comment]
OK, let's think out of the box - why not keep sequencer signature inside header itself and abandon the entire Tendermint-style "last commit" approach? We can always "generate" Tendermint-compatible commits based on this data.

CC @liamsi @nashqueue

**Comment by Wondertan** [comment]
Noting here that the current state of the go-header allows read-only operations for headers. This is so because celestia-node never had a need to make any changes to the header body.

Your case is more advanced and we can consider extending the Header interface with the signature business. Please don't limit yourself on current state of the lib and think how we can add more feature there basing Rollkit product needs.

There could be run an additional gossiping process for signatures implemented in the header lib that appends signatures to the header as they go until some condition is met(2/3 of power signed it or so)

**Comment by gupadhyaya** [comment]
> OK, let's think out of the box - why not keep sequencer signature inside header itself and abandon the entire Tendermint-style "last commit" approach? We can always "generate" Tendermint-compatible commits based on this data.
> 
> CC @liamsi @nashqueue
you mean keeping the last commit signature in the header? i thought about this and i dont see a problem. only thing to consider would be if the signatures size grow when multiple sequencer is supported as there won't be signature aggregation with the current scheme.

**Comment by nashqueue** [comment]
The best option would be to add the signature to the header. We can extend this at some point to have other features/signature schemes.

**Comment by gupadhyaya** [comment]
@tzdybal 
as i see, these are our options:
1. totally remove the sequencer header gossip and rely completely on header exchange (this will require fetching commit/sequencer-signature from the DA layer). note that, sequencer will still broadcast the headers as part of header exchange. if we enable syncing for sequencer nodes, the header exchange will be sufficient even for multi-sequencer setup.
2. trim down the sequencer to only gossip commit/sequencer-signature.
3. add sequencer signature to header.
for now, should we proceed with 1 and wait to see if we need to evolve our header and block structures to meet the multiple execution envs? for example, the header/block may well just be interfaces with concrete implementations provided for cosmos-sdk, evm, move-vm, solana-vm, etc?

**Comment by nashqueue** [comment]
Why does the first option require fetching the commit/sequencer from the DA-Layer?

**Comment by gupadhyaya** [comment]
> Why does the first option require fetching the commit/sequencer from the DA-Layer?

to save the block, you need commit which is already in the block that is available in DA. the gossip of the signed header (header+commit) by the sequencer was helping sync faster.

**Comment by nashqueue** [comment]
fixed by #766

**Comment by liamsi** [comment]
> fixed by https://github.com/rollkit/rollkit/pull/766

It's a bit unclear what happened here as the linked PR was not merged but closed.
