### ISSUE TITLE
Rollkit CLI

### ISSUE THREAD

**Issue by Ferret-san** [rollkit/rollkit#745]
Rollkit should have a cli tool similar to that of [tendermint](https://github.com/tendermint/tendermint/tree/main/cmd/tendermint). This tool would allow developers to:

- initialize all the configuration needed to run a rollkit node of any kind `rollkit init`
- run a node and connect it to an application through a proxy `rollkit node --proxy_app=unix://example.sock`

As well as other commands that developers find useful.

**Comment by nashqueue** [comment]
[Documentation of tendermint CLI ](https://docs.tendermint.com/v0.33/introduction/install.html)

**Comment by Manav-Aggarwal** [comment]
cc: @Ferret-san
