### ISSUE TITLE
Sign current Header before posting it. 

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#768]
The current rollkit block has this format:

- Header
- Body
- LastCommit

LastCommit:

- headerhash
- height
- signature

One problem arises: I am Sequencer A, and I publish a block to Celestia. Now Sequencer B wants to publish a Block. Sequencer B cannot publish a Block until it gets a signed Header of Sequencer A. Sequencer A will be able to "stall" Sequencer B. I can only create LastCommit if I have the signed header. I only get the signed header through gossiping.

Proposed Format:
~~Header {
lastheaderhash
currentblockhash
}
CurrentCommit{
signature of header
}
Body~~

Proposed Format:
SignedHeader
Body

@gupadhyaya @S1nus What do you think 

This will give us a pretty good way of checking the signature and using it for centralised/decentralised sequencing. This could also unblock #735

**Comment by gupadhyaya** [comment]
moreover, there won't be signed header gossip after https://github.com/rollkit/rollkit/pull/766 is merged. the sequencer 1 will broadcast the header and also publish the block to DA, hence the sequencer 2 should be able to get the header from header exchange and block from DA. not sure if i see the problem here. if sequencer 1 withholds the header, it can always be considered censoring?

**Comment by gupadhyaya** [comment]
the problems we plan to address:
* eliminate sequencer stalls: sequencer B that wants to continue after sequencer A should have access to current commit signature, such that it can download the last block from DA and verify the header's signature and continue building the next block
* light nodes should be able to access the last commit signature in the header without going through DA as they only rely on gossiped headers

here are the modifications we propose:
* remove `LastCommitHash` from `Header` and directly add `LastCommitSignatures`, such that gossiped headers are alone sufficient for light nodes to validate/maintain the header chain.
* replace `LastCommit` in the `Block` with `CurrentCommit` or simply called as `Commit`, which holds the sequencer signature for the current block header. this way, the new sequencer joining the system is not stalled by the previous sequencer and only need to fetch the last DA block and start producing new blocks on top of it.

**Comment by gupadhyaya** [comment]
@nashqueue we don't need to do the `SignedHeader` (which contains Header and Signature) gossip for light nodes, as light nodes can build the header chain using the gossiped headers which have last commit signatures. this will drastically reduce the amount of changes needed.

**Comment by cryptskii** [comment]
quencer stalls and improve accessibility of the last commit signature for light nodes. Here's a possible way to implement the proposed modifications:

Remove LastCommitHash from Header and directly add LastCommitSignatures:
Header {
lastheaderhash,
lastcommitsignatures[],
currentblockhash
}

Replace LastCommit in the Block with CurrentCommit or simply called as Commit, which holds the sequencer signature for the current block header:
Block {
Header {
lastheaderhash,
lastcommitsignatures[],
currentblockhash
}
Body {
...
}
Commit {
sequencer signature for current header
}
}

This way, the sequencer signature for the current block header is available in the block itself, and a new sequencer can simply fetch the last DA block and start producing new blocks on top of it without being stalled by the previous sequencer. Light nodes can also build the header chain using the gossiped headers which have last commit signatures, and there would be no need to gossip SignedHeaders separately.

**Comment by cryptskii** [comment]
// Define the modified Header struct
type Header struct {
    LastHeaderHash       []byte
    LastCommitSignatures [][]byte
    CurrentBlockHash     []byte
}

// Define the modified Block struct
type Block struct {
    Header Header
    Body   []byte
    Commit []byte // sequencer signature for current header
}

**Comment by nashqueue** [comment]
> we don't need to do the SignedHeader (which contains Header and Signature) gossip for light nodes, as light nodes can build the header chain using the gossiped headers which have last commit signatures. this will drastically reduce the amount of changes needed.

Unfortunetly this does only work in the happy case . There a lot of ways where this breaks in terms of liveness and fraud. I will explain what happens when fraud happens.

Lets imagine a header chain:

H4[S(H3)] -> H5[S(H4)] -> H6[S(H5)] -> H7[S(H6)] -> H8[S(H7)] -> H9[S(H8)] -> H10[S(H9)] -> H11[S(H10)]

Now Fraud happens in Block 8. To validate the Fraud, we must validate Header 8, which references Block 8. We can only do that if we have the signature of Header 8.
In this scheme, we only get the signature of Header 8 if we get Header 9. We only get Header 9 if we produce a Block 9. This means that the next Sequencer would need to produce a block on top of the fraudulent block just so that we can prove that the previous block is fraudulent. (This is already a problem)

Of course, the person who creates the malicious block 8 will not gossip the signature of Header 8 if he is not forced to do so. 

The only way to force the malicious sequencer to gossip the signature is by making the signature available with the header. Meaning it needs to be in the same blob as the Header.

**Comment by nashqueue** [comment]
This is not a problem for a centralized sequencer scheme with pessimistic mode, but the moment we want anything more we will either have liveness or fraud proof problems

**Comment by Manav-Aggarwal** [comment]
Closing since this is not a problem for a centralized sequencer scheme
