### ISSUE TITLE
Merkelize some hashes in block header

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#77]
Currently, block header contains multiple hashes, that can be "merkelized" into single hash.
There is [similar discussion](https://github.com/tendermint/tendermint/issues/7860) in Tendermint repo.

Origin: https://github.com/lazyledger/optimint/pull/73#discussion_r644734732

ref:  
- tendermint/tendermint#7860
- tendermint/tendermint#7915

**Comment by Manav-Aggarwal** [comment]
Not relevant anymore
