### ISSUE TITLE
Refactor (Header, Last Commit) into Signed Header

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#773]
Remove LastCommit from the Block as Current Commit will be saved.
 Current Commit + Header is Signed Header. 

Before: 
```go
message Block {	
	Header header = 1;
	Data data = 2;
	Commit last_commit = 3;
}

message SignedHeader {
	Header header = 1;
	Commit commit = 2;
}

message Commit {
	uint64 height = 1;
	bytes header_hash = 2;
	repeated bytes signatures = 3;
}
```

After:
```go
message Block {	
	SignedHeader signedHeader = 1;
	Data data = 2;
}

message SignedHeader {
	Header header = 1;
	Commit commit = 2;
}

message Commit {
	uint64 height = 1;
	bytes header_hash = 2;
	repeated bytes signatures = 3;
}
```

**Comment by gupadhyaya** [comment]
@nashqueue 
```
message Commit {
	uint64 height = 1;
	bytes header_hash = 2;
	repeated bytes signatures = 3;
}
```
why do we need to repeat `height` and `header_hash` in the `Commit`? these are already there in the `SignedHeader.Header`? may be we can just have:
```
message SignedHeader {
	Header header = 1;
	repeated bytes signatures = 2;
}
```

**Comment by nashqueue** [comment]
Agree

**Comment by gupadhyaya** [comment]
actually, we also need to add public_key to both header and signed header to be able to verify the signature. currently, we have proposer address from which we cannot get the public key.
```
type Header struct {
...
repeated bytes last_signatures = 3;
bytes last_public_key = 3;
...
}
```
```
message Commit {
	bytes signer_public_key = 1;
	repeated bytes signatures = 3;
}
message SignedHeader {
	Header header = 1;
	Commit commit = 2;
}
```

**Comment by nashqueue** [comment]
We already have 

```go
	bytes proposer_address = 10;
```

So that should be enough for now to verify the signature.

**Comment by gupadhyaya** [comment]
i dont think so. i checked the code. proposer addr is only the first 20 bytes of the sha3 of public key. i dont think we can get the public key back using proposer addr. note that, we need public key for verifying the signature

**Comment by gupadhyaya** [comment]
@nashqueue there is also another issue. both `Header` and `SignerHeader` need to have the signer public keys. Otherwise, we won't be able to capture, if there is a change in the sequencer. 
```
message Header {
     repeated bytes last_signer_keys = ...
     repeated bytes last_signatures = ...
}
```
and
```
message Commit {
     repeated bytes signer_keys = 1;
     repeated bytes signatures = 1;
}

message SignedHeader {
	Header header = 1;
	Commit commit = 2;
}
```
