### ISSUE TITLE
Remove Aggregatorhash from Header and add aggregator set

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#784]
In rollkit.proto we have 	

```go
// Hash of block aggregator set, at a time of block creation
	bytes aggregators_hash = 12;
```

Replace it with:

```go
// Block aggregator set, at a time of block creation
	repeated bytes signatures = 12;
```

**Comment by Manav-Aggarwal** [comment]
Since the `vA` release for Rollkit will enforce centralized sequencers and support for multi-sequencer schemes will only be relevant post `v1` release, this issue should block until then.

**Comment by Manav-Aggarwal** [comment]
`aggregators_hash` was removed in https://github.com/rollkit/rollkit/pull/1301
