### ISSUE TITLE
Set the validator set and next signer from the staking module

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#797]
Get the public key and the sequencer set from the staking module. 
Original discussion: https://github.com/rollkit/rollkit/pull/788/files#r1139431177
```go

               // set the validator set using the signer's public key
		// TODO(ganesh): need to hook into a module that selects signers

		pubKey, err := m.proposerKey.GetPublic().Raw()
		if err != nil {
			return err
		}
		block.SignedHeader.Validators = types.ValidatorSet{Validators: []types.Validator{{PublicKey: pubKey}}}
```
Comment by @nashqueue 
> Maybe the previous header could include the next signer? I think this will be a query to the staking module?

**Comment by Manav-Aggarwal** [comment]
Handled by https://github.com/rollkit/rollkit/issues/1673
