### ISSUE TITLE
Lazy Aggregator mode does not build a first block

### ISSUE THREAD

**Issue by S1nus** [rollkit/rollkit#802]
**To replicate**:
run the tutorials with `--rollkit.lazy_aggregator true` enabled. Notice that it does not build a first block. When you attempt to query state, it will panic with a nil pointer, presumably because genesis is never executed.

**Possible fix**:
Change the behavior of lazy aggregator mode, force it to build an initial block

**Comment by jcstein** [comment]
related details: https://github.com/rollkit/rollkit/issues/792#issuecomment-1480923148

**Comment by jcstein** [comment]
this behavior is still occuring so we should reopen this issue

**Comment by S1nus** [comment]
> this behavior is still occuring so we should reopen this issue

it is broken again, need to figure out why the fix stopped working

**Comment by jcstein** [comment]
Should be closed with https://github.com/rollkit/rollkit/releases

**Comment by jcstein** [comment]
I'm fairly certain this is not an issue, and that there is an issue with the local-celestia-devnet or its dependencies. Lazy aggregation is working as expected on Blockspace Race. cc @S1nus 🫡

**Comment by nashqueue** [comment]
@S1nus Is this issue still a problem or was it fixed with #823 and #816 ?

**Comment by jcstein** [comment]
Fixed afaik

**Comment by nashqueue** [comment]
fixed by #803
