### ISSUE TITLE
types: reuse tendermint types

### ISSUE THREAD

**Issue by tuxcanfly** [rollkit/rollkit#805]
`Validator` / `ValidatorSet` structs can be reused from tendermint. This also helps us to get `Proposer` by reusing tendermint's `ValidatorSet.GetProposer`.

**Comment by tzdybal** [comment]
Historical context: from very beginning we tried to minimize dependencies on Tendermint. This is why custom types were introduced. Originally we planned to just copy-paste `GetProposer` algorithm into repository.
