### ISSUE TITLE
Check if abciValUpdates is not nil

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#821]
App Developers can make Endblock response nil. What happens if there are no more validators in the staking module? How do we deal with a nil response? 

https://github.com/rollkit/rollkit/blob/6a8b5d8c1d4c808bff1f7aa76b398793f47c5f94/state/executor.go#L149

**Comment by Manav-Aggarwal** [comment]
Since the default response for `EndBlock` includes validator set changes, if any, this is not an issue. There does not seem to be a clear scenario where an app developer would need to change this default response to nil.
