### ISSUE TITLE
Cannot run two nodes

### ISSUE THREAD

**Issue by S1nus** [rollkit/rollkit#828]
Following the [gm tutorial](https://rollkit.dev/docs/tutorials/gm-world/), after spinning up a sequencer and sucesfully querying it, attempting to start a separate full node in another terminal does not work.

**To replicate**:
1. follow the gm-world tutorial to start an aggregator node
2. start a full node like so, but ensure that NAMESPACE_ID, DA_BLOCK_HEIGHT, and the p2p-seed corresponds correctly with the other node
````
#!/bin/sh

#VALIDATOR_NAME=validator1
#CHAIN_ID=gm
#KEY_NAME=gm-key
#CHAINFLAG="--chain-id ${CHAIN_ID}"
#TOKEN_AMOUNT="10000000000000000000000000stake"
#STAKING_AMOUNT="1000000000stake"

CHAIN_ID=gm
BASE_DIR="$HOME/.fn_gm"

rm -rf $BASE_DIR

gmd --home "$BASE_DIR" init FullNode --chain-id $CHAIN_ID

cp -R "$HOME/.gm/config/genesis.json" "$BASE_DIR/config/genesis.json"

NAMESPACE_ID="27e3b546191d5fbb"
DA_BLOCK_HEIGHT=2

#ignite chain build
#gmd tendermint unsafe-reset-all
#gmd init $VALIDATOR_NAME --chain-id $CHAIN_ID

#gmd keys add $KEY_NAME --keyring-backend test
#gmd add-genesis-account $KEY_NAME $TOKEN_AMOUNT --keyring-backend test
#gmd gentx $KEY_NAME $STAKING_AMOUNT --chain-id $CHAIN_ID --keyring-backend test
#gmd collect-gentxs

gmd --home $BASE_DIR start --log_level debug --rollkit.da_layer celestia --rollkit.da_config='{"base_url":"http://localhost:26659/","timeout":60000000000,"fee":6000,"gas_limit":6000000}' --rollkit.namespace_id $NAMESPACE_ID --rollkit.da_start_height $DA_BLOCK_HEIGHT --rpc.laddr tcp://127.0.0.1:36657 --grpc.address 127.0.0.1:9390 --grpc-web.address 127.0.0.1:9391 --p2p.seeds "12D3KooWBCEw2FP3pJ7K8ALVhFpW8JW5KzLerp87AVAm2En2fjJp@127.0.0.1:26656" --p2p.laddr "0.0.0.0:36656"
````
3. Query the second node like so: `curl localhost:36657/block\?height=1`
4. Observe that it does not find block 1

**Comment by S1nus** [comment]
might be related to https://github.com/rollkit/rollkit/issues/809

**Comment by Manav-Aggarwal** [comment]
This is resolved after testing of p2p blocksync changes. Was tested as part of updating: https://github.com/rollkit/docs/pull/241/files

confirmed that I'm able to run two nodes and they're able to sync blocks that are queryable.
