### ISSUE TITLE
header exchange throws store already initialized error

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#846]
After the syncer is enabled for aggregator nodes, there exists two workflows that tries to initialize the header store using the genesis block which causes the 2nd to fail with error `store already initialized`. A simple fix of skipping the initialization if already initialized should fix the issue, however need to ensure that fix will work as expected.

```
10:36AM ERR failed to start syncer after initializing header store error="store already initialized" module=HeaderExchangeService
```

**Comment by gupadhyaya** [comment]
current behavior of aggregator is that, it does not run syncer, but it will append the created headers directly to the header store. currently the syncer.go in the go-header package does not allow both self append and syncer to work concurrently, hence the aggregator does not run syncer. see the error below:
```
2023-05-22T18:06:48.718-0500	ERROR	header/sync	sync/sync.go:211	syncing headers	{"from": 2, "to": 2, "err": "header/store: non-adjacent: head 2, attempted 2"}
6:06PM DBG retrieved potential blocks daHeight=158 module=BlockManager n=1
```
@Wondertan can syncer check if the header store is already updated and skip syncing in that case?

if the aggregator has to do both 1) append the created headers directly to header store and 2) run the syncer in case to support multiple aggregator settings, the syncer has to allow this. note that, directly appending the self created headers is necessary to prevent withholding attacks (if we don't directly append and simply broadcast and hope that gossip will eventually append it).

**Comment by Wondertan** [comment]
> @Wondertan can syncer check if the header store is already updated and skip syncing in that case?

Do you mean complete skip of syncing or skip appending the particular header that is already in the store?

When you directly append headers to the Store, does Syncer additionally re-requests from elsewhere the same direct headers?

**Comment by gupadhyaya** [comment]
> same

we need syncer to skip the syncing of headers which are directly appended to store by the node. in terms of code, it has to hit the line: https://github.com/celestiaorg/go-header/blob/main/sync/sync.go#L190, but from the error logs (i added couple of more), we can see that storeHead (https://github.com/celestiaorg/go-header/blob/main/sync/sync.go#L184) is getting stale value. not sure why.

its two different go-routines: while the syncer is running in the background, the node is also creating headers, appending to its store and broadcasting it. https://github.com/rollkit/rollkit/blob/main/node/full.go#L244 in a different go-routine.
