### ISSUE TITLE
support for emitting events

### ISSUE THREAD

**Issue by pciavald** [rollkit/rollkit#865]
i'm transitioning my project from tendermint to rollkit, and seem to have lost support for events.

## how to reproduce

after scaffolding a chain, module and model with ignite, add the following:

in `{chain_name}/x/{module_name}/keeper/msg_server_{model_name}.go`:
```go
func (k msgServer) CreateAgency(goCtx context.Context, msg *types.MsgCreateAgency) (*types.MsgCreateAgencyResponse, error) {
	ctx := sdk.UnwrapSDKContext(goCtx)

	var agency = types.Agency{
		Creator:         msg.Creator,
		Owner:           msg.Owner,
		Name:            msg.Name,
		PaymentProvider: msg.PaymentProvider,
		PaymentAddress:  msg.PaymentAddress,
	}

	id := k.AppendAgency(
		ctx,
		agency,
	)

+	ctx.EventManager().EmitTypedEvent(&types.EventCreateAgency{
+		Id: id,
+	})

	return &types.MsgCreateAgencyResponse{
		Id: id,
	}, nil
}
```

in `{chain_name}/proto/{chain_name}/{module_name}/{model_name}.proto` append:
```proto
message EventCreateAgency {
	uint64 id = 1;
}
```

## expected behaviour 

After doing so, creating an agency with 
```
exampled tx fab create-agency <args>
```
should result in a transaction which has a `logs` key filled with the event, for other nodes to listen on.

## actual behaviour

The returned transaction has the following form:
```py
{
  'code': 0,
  'codespace': '',
  'data': '',
  'events': [],
  'gas_used': '0',
  'gas_wanted': '0',
  'height': '0',
  'info': '',
  'logs': [],
  'raw_log': '[]',
  'timestamp': '',
  'tx': None,
  'txhash': '07F03D0BE56D80E1A9B600B06681D7016384118B17BC1CA16BC2A720513B4744'
}
```
and the code that I had to watch the event and get the created agency's `id` is not working anymore:
```py
id = findAttribute(findEvent(ret["logs"][0]["events"], event), "id")[1:-1]
```

**Comment by mindstyle85** [comment]
@nashqueue any timeline for this? its preventing this BSR participant to deploy their rollup

**Comment by tzdybal** [comment]
Something is wrong, as there is no error (`code` is `0`), but no gas was used, height is invalid (`0`), there is no `timestamp` and no `tx`.
@pciavald Are you sure your chain is actually running (producing blocks)?

**Comment by tzdybal** [comment]
@pciavald if you could provide a link to source code, then we will be able to reproduce/debug the issue.

**Comment by pciavald** [comment]
To reproduce the issue, you can follow these steps:
- clone https://github.com/zkvalidator/ignite-manager
- at the repo root, run `./run.sh build.yml` (it will take a few minutes), it will:
  - scaffold the chain, module and models as per build.yml
  - build the client binary
  - start a celestia local devnet node
  - run the rollup
- run:
```
docker exec -it ignite-manager \
  examplechaind tx examplemodule \
  create-entity-name \
  test \
  0 \
  --keyring-backend test \
  --from alice \
  --yes \
  --chain-id examplechain-0
```

**Comment by pciavald** [comment]
@tzdybal i've just noticed i had forgotten to push a fix for the yml config, if you tried and it failed on token issues, it's fixed

**Comment by tzdybal** [comment]
After pulling latest changes I still get the same error as previously:
```
ignite-manager  | INFO:root:Starting...
ignite-manager  | INFO:root:Loading configuration from 'config.yml'...
ignite-manager  | DEBUG:root:Configuration loaded: {'version': 1, 'accounts': [{'name': 'alice', 'coins': ['200000000stake', '20000stake'], 'mnemonic': 'winter blur imitate this open palace reward steel local noodle believe into evil other rebuild ready fuel someone body capital review mixture absurd seminar'}, {'name': 'bob', 'coins': ['100000000stake', '10000stake'], 'mnemonic': 'mammal artist elbow chaos oak gym practice oblige local decrease fetch boat inner same artist veteran catalog cannon fat forest tail boat must observe'}], 'validators': [{'name': 'alice', 'bonded': '100000000stake'}], 'init': {'config': {'api': {'enable': True, 'swagger': False, 'address': 'tcp://0.0.0.0:1317', 'max-open-connections': 1000}}}, 'client': {'openapi': {'path': 'docs/static/openapi.yml'}, 'typescript': {'path': 'ts-client'}, 'vuex': {'path': 'vue/src/store'}}, 'faucet': {'name': 'alice', 'coins': ['5token', '100000stake']}}
ignite-manager  | Traceback (most recent call last):
ignite-manager  |   File "/app/src/main.py", line 285, in <module>
ignite-manager  |     main()
ignite-manager  |   File "/app/src/main.py", line 269, in main
ignite-manager  |     chain_name = config["chain"]["name"]
ignite-manager  | KeyError: 'chain'
ignite-manager exited with code 1
[+] Running 1/0
 ✔ Container ignite-manager  Removed     
 ```

**Comment by pciavald** [comment]
@tzdybal it seems you're running `./run.sh config.yml` instead of `./run.sh build.yml`

**Comment by pciavald** [comment]
what's the output of `ls -la go_root/bin` at the repo root ?

**Comment by tzdybal** [comment]
There are only `protoc-` files. The chain was not installed successfully. I'll try to re-do everything, starting with clean working directory.

**Comment by pciavald** [comment]
my discord handle is peac#6754 if that's more convenient

**Comment by tzdybal** [comment]
It seems that default broadcast mode works differently with Rollkit. After querying the TX by hash, events are visible.

**Comment by nashqueue** [comment]
If possible, we should keep the discussion in Github, so the future conclusion can reference this issue.

**Comment by pciavald** [comment]
@nashqueue the discussion we had on discord was not relevant to the issue but to making my project work on @tzdybal 's computer so they can reproduce. We found that the events are managed differently but are still accessible by querying the transaction after it was emitted. I'll do a write-up of my findings when I get back on my computer!

**Comment by pciavald** [comment]
We're still working on making it easy to compare tendermint and rollkit results, but here's what tendermint returns in a similar scenario:

```
code: 0
codespace: ""
data: 12350A332F7465745F74656E6465726D696E742E74657474656E6465726D696E742E4D7367437265617465506F7374526573706F6E7365
events:
- attributes:
  - index: true
    key: ZmVl
    value: ""
  - index: true
    key: ZmVlX3BheWVy
    value: Y29zbW9zMWNhNHU2dng0bjN6NXRzMGZhaDcwMzhtNTNsdWo4eGM4NDIzeDdj
  type: tx
- attributes:
  - index: true
    key: YWNjX3NlcQ==
    value: Y29zbW9zMWNhNHU2dng0bjN6NXRzMGZhaDcwMzhtNTNsdWo4eGM4NDIzeDdjLzA=
  type: tx
- attributes:
  - index: true
    key: c2lnbmF0dXJl
    value: T2I4Y3RGNkVKYmJqakJTSWo0S21adWlBVXk1MzRHWVFtZzhVTnZSY0w4WnlRSU9jcDJIa3RZRWRVcW5VWDJDYXB3Yko4bW1ybzdsYldMSUtiWTlBVmc9PQ==
  type: tx
- attributes:
  - index: true
    key: YWN0aW9u
    value: L3RldF90ZW5kZXJtaW50LnRldHRlbmRlcm1pbnQuTXNnQ3JlYXRlUG9zdA==
  type: message
gas_used: "62633"
gas_wanted: "200000"
height: "8367"
info: ""
logs:
- events:
  - attributes:
    - key: action
      value: /tet_tendermint.tettendermint.MsgCreatePost
    type: message
  log: ""
  msg_index: 0
raw_log: '[{"msg_index":0,"events":[{"type":"message","attributes":[{"key":"action","value":"/tet_tendermint.tettendermint.MsgCreatePost"}]}]}]'
timestamp: ""
tx: null
txhash: 978C0C57C73BB85B91AF5FE3F8A8E9B65CE9CADC707DBD9B9D66CA321C443A98
```

**Comment by tzdybal** [comment]
I think so.
