### ISSUE TITLE
Adding a Sequencer that is not part of genesis

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#866]
Currently, we have all Sequencers in the Genesis file. 
This test case wants to cover the test case that initlizises a validator set, say 2 sequencers.
A third Node is running that is not part of Genesis. Does CreateValidator and becomes a new validator. 
Starts running a sequencer.

**Comment by Manav-Aggarwal** [comment]
This is covered by the staking module added by Decentrio.
