### ISSUE TITLE
Test out what happens if Sequencers submit 2 Blocks in a row even if priorities change

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#870]
What if we have a malicious sequencer that submits a valid block but is not supposed to be a sequencer?
Publishes block in height h and is the correct sequencer. It also publishes block in height h+1, but it is the wrong sequencer.  

Expected behaviour: Signature check fails for Full Nodes.

**Comment by Manav-Aggarwal** [comment]
cc: @S1nus

**Comment by Manav-Aggarwal** [comment]
Same as https://github.com/rollkit/rollkit/issues/1280, closed.
