### ISSUE TITLE
Sequencer submits 2 blocks at the same height.

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#871]
Sequencer submits 2 blocks at the same height h but with different content. 

Current Expected Behaviour: We take FCFS as a fork choice rule.
But wished behaviour: Sequencer gets slashed or maybe fullnodes should halt

**Comment by Manav-Aggarwal** [comment]
cc: @S1nus

**Comment by Manav-Aggarwal** [comment]
Duplicate of https://github.com/rollkit/rollkit/issues/1672
