### ISSUE TITLE
Specify aggregator behaviour if data availability layer is not available

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#88]
_Originally posted by @evan-forbes in https://github.com/celestiaorg/optimint/pull/82#discussion_r677657935_

**Comment by liamsi** [comment]
> What are the plans for if tx is not accepted promptly in the data availability layer?

This kind of edge-case is also a good question for @adlerjohn or @musalbas IMO. I think the aggregator should just continue to retry (maybe a limited amount of times).

**Comment by musalbas** [comment]
They should retry, unless another valid block by another aggregator was included, in which case they should generate a new block, as some of their block's transactions may have already been included.

**Comment by adlerjohn** [comment]
Agree with @musalbas. There's also the possibility of continuing to build new blocks optimistically even if the current block isn't accepted by the DAL yet.

**Comment by Manav-Aggarwal** [comment]
We have retries, exponential backoffs, and p2p blocksync. Still need to put it in the spec.
