### ISSUE TITLE
The application exits with exit code `0` when panicking

### ISSUE THREAD

**Issue by smuu** [rollkit/rollkit#898]
## Decription

The application exits with exit code `0` when panicking.

## Expected behavior

Exit code `0` indicates that the program executed successfully without any errors. This is not the case when the program panics. So I would expect another exit code than `0`.

## Reproduce

You can panic the gm rollup using: https://github.com/rollkit/rollkit/issues/883

**Comment by tuxcanfly** [comment]
go panics with exit code 2. I believe the exit code here is coming from docker

> docker-gm-1 exited with code 0
