### ISSUE TITLE
Error `store already initialized` when starting rollup

### ISSUE THREAD

**Issue by smuu** [rollkit/rollkit#899]
### Steps to reproduce it

To reproduce this behavior, you will start a consensus validator and DA bridge using `local-celestia-devnet` and start the gm rollup on top of it.

1. Clone [rollkit/gm](https://github.com/rollkit/gm)
2. Navigate to the `docker` directory
3. Start local-celestia-devnet in the background with `docker compose up celestia -d`
4. Build the rollup with `docker compose build --no-cache`
5. Start the rollup node with `docker compose up gm`
6. Wait until you see the error in the shell
7. To clean up, you can use `docker compose down`

### Expected result

No errors.

### Actual result

```
ERR failed to start syncer after initializing header store error="store already initialized" module=HeaderExchangeService
```

**Comment by gupadhyaya** [comment]
duplicate #846
