### ISSUE TITLE
Errors when restarting rollup node

### ISSUE THREAD

**Issue by smuu** [rollkit/rollkit#900]
### Steps to reproduce it

To reproduce this behavior, you will start a consensus validator and DA bridge using `local-celestia-devnet` and start the gm rollup on top of it.

1. Clone [rollkit/gm](https://github.com/rollkit/gm)
2. Navigate to the `docker` directory
3. Change the version of `ghcr.io/rollkit/local-celestia-devnet` to `v0.8.2` in the `docker-compose.yaml` file (Never versions throw other errors)
4. Start local-celestia-devnet in the background with `docker compose up celestia -d`
5. Build the rollup with `docker compose build --no-cache`
6. Start the rollup node with `docker compose up gm`
7. Let the rollup produce 1-2 blocks
8. Stop the rollup by pressing `CTRL+C` in the rollup terminal
9. Restart the rollup node with `docker compose up gm` (This will reuse the previous container so that it will get started with data from the previous run)
10. Wait until you see the error in the shell
11. To clean up, you can use `docker compose up down`

### Expected result

No errors.

### Actual result

Sometimes I can see the error

```
ERR DA layer submission failed error="rpc error: code = Unknown desc = failed to subscribe to tx: already subscribed" attempt=1 module=BlockManager
```

and always this error

```
ERR failed to write block header to header store error="header/store: non-adjacent: head 1, attempted 3" module=HeaderExchangeService
```

**Comment by Manav-Aggarwal** [comment]
Will be covered by https://github.com/rollkit/rollkit/issues/1431.
