### ISSUE TITLE
Dependabot wasn't able to update downloading 

### ISSUE THREAD

**Issue by smuu** [rollkit/rollkit#906]
Dependabot wasn't able to update downloading

The module path downloading found in your `go.mod` doesn't match the actual path `github.com/ipfs/go-ds-badger2` found in the dependency's `go.mod`.

Updating the module path in your `go.mod` to github.com/ipfs/go-ds-badger2 should resolve this issue.
[Learn more](https://docs.github.com/github/managing-security-vulnerabilities/troubleshooting-dependabot-errors)

See here: https://github.com/rollkit/rollkit/network/updates/652652353

**Comment by gupadhyaya** [comment]
update by @tzdybal https://github.com/ipfs/go-ds-badger3/issues/3

**Comment by tzdybal** [comment]
> update by @tzdybal issue: [ipfs/go-ds-badger3#3](https://github.com/ipfs/go-ds-badger3/issues/3) and fixing PR: [ipfs/go-ds-badger3#4](https://github.com/ipfs/go-ds-badger3/pull/4)

This is already merged, and v0.1.4 released. Dependabot [works fine again.](https://github.com/rollkit/rollkit/network/updates/679192471)
