### ISSUE TITLE
Rollkit sequencer error: module=HeaderExchangeService

### ISSUE THREAD

**Issue by nodebreaker0-0** [rollkit/rollkit#923]
`ERR failed to write block header to header store error="header/store: non-adjacent: head 168, attempted 10977" module=HeaderExchangeService
`

version: github.com/rollkit/rollkit v0.7.4
sample: https://github.com/b-harvest/crescent/tree/celescent

Sequencer nodes in the Sovereign Role will throw the above error after a period of time.

We don't yet know the exact conditions that trigger this error.

**Comment by nashqueue** [comment]
might be duplicate of #908

**Comment by gupadhyaya** [comment]
@nodebreaker0-0 please see my response in https://github.com/rollkit/rollkit/issues/908#issuecomment-1570986001
