### ISSUE TITLE
Implementing IBC in Rolkit

### ISSUE THREAD

**Issue by nodebreaker0-0** [rollkit/rollkit#924]
I'm currently testing IBC between the sample rollup below and the blockrace version of Celestia App, and I've seen a third party crash.

hermes version: 1.4.0
celestia version: 0.13.0
rollkit version: 0.7.4

I can't think of any specific requirements yet,

I think it will require a lot of modifications to the Tendermint logic customized in Rolkit.

- Need an interface to consensus information
- latest_block_hash
- node id
- latest_app_hash
- earliest_block_hash
- And information about keys

By default, Hermes requests structured information via RPCs in the chain, and either converts it back to its original format when replying to a rollkit, or gives it to you,

or you may need to issue an issue to Hermes.

I think using IBC would require a lot of customization, it seems to be smoother to use a setting layer than this, you need a transport layer between rollups in the data layer to allow tokens to move through Celestia.

The error below is caused by the nodeid being a libp2p address format.

```hermes --config ibc.toml create channel --order unordered --a-chain cre-test --b-chain blockspacerace-0 --a-port  transfer --b-port transfer --new-client-connection```

`ERROR failed to spawn chain runtime: relayer error: RPC error to endpoint http://127.0.0.1:16657/: serde parse error: expected 40-character hex string, got "12D3KooWGFoiWM8CwpiQqkT2jDFTybDyarkaAx1mo8VRQZMbygJ9" at line 1 column 153`

hermes config
```
ubuntu@ip-172-31-46-58:~$ cat ibc.toml 
[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 101
clear_on_start = true
tx_confirmation = false

[rest]
enabled = true
host = '0.0.0.0'
port = 53000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 53001

[[chains]]
id = 'cre-test'
rpc_addr = 'http://127.0.0.1:16657'
grpc_addr = 'http://127.0.0.1:19090'
websocket_addr = 'ws://127.0.0.1:16657/websocket'

rpc_timeout = '20s'
account_prefix = 'cre'
key_name = 'cre'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 400000
max_gas = 3000000
gas_price = { price = 0.01, denom = 'ucre' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'B-Harvest'

[chains.packet_filter]
policy = 'allow'
list = [
 #['transfer', 'channel-40']     # Crypto.org
]
# fee_granter = ''


[[chains]]
id = 'blockspacerace-0'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
websocket_addr = 'ws://127.0.0.1:26657/websocket'

rpc_timeout = '20s'
account_prefix = 'celestia'
key_name = 'cel'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 400000
max_gas = 3000000
gas_price = { price = 0.001, denom = 'utia' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '15s'
max_block_time = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'B-Harvest'

[chains.packet_filter]
policy = 'allow'
list = [
 #['transfer', 'channel-40']     # Crypto.org
]
# fee_granter = ''
```

>

**Comment by Manav-Aggarwal** [comment]
Should be handled in https://github.com/rollkit/docs/pull/324, please reopen if relevant
