### ISSUE TITLE
Extend Proof Validate to accommodate all checks

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#932]
checks in Proof.Validate:
=====

- [ ] Shares are included in Celestia posted ( unblocked after Blobmodule **V2**)
- [ ] Shares come from the correct block from the correct header ( unblocked after Blobmodule **V2**)
- [ ] Badly formatted Data (unblocked when we have OutofContext parsing and ISR serialization) 
- [ ] Threshold checks for state witness sizes (good to have)
- [x] #981
- [x] #982

**Comment by nashqueue** [comment]
Add validation methods to #570

**Comment by gupadhyaya** [comment]
Proof interface is very lightweight and we might not be able to perform all the checks in Proof.Validate function: https://github.com/rollkit/rollkit/blob/main/types/state_fraud_proof.go#L34

**Comment by Manav-Aggarwal** [comment]
https://github.com/rollkit/rollkit/issues/1632#issuecomment-2408212822
