### ISSUE TITLE
Implement proper way of halting node after state fraud proof

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#933]
Check if the context cancel leads to proper halting of the node.

https://github.com/rollkit/rollkit/blob/main/block/manager.go#L298
https://github.com/rollkit/rollkit/blob/main/node/full.go#L265

**Comment by gupadhyaya** [comment]
if the nodes stop after verifying the fraud, they won't be able to serve any other full nodes that want to sync the fraud proof. what should be the intended behavior is more of a design question than engineering

**Comment by nashqueue** [comment]
Intended behaviour when valid fraud happens in height h **without recovery**: 
- full node process fraud proof and gossips it 
- halt gossiping new blocks after height h
- halt gossiping new headers after height h
- continue sync old blocks for other full nodes to catch up
- continue sync old headers for other full/ligh nodes to catch up 
- continue serving fraud proofs for new nodes joining the network
- Stop processing fraud proofs after h
- Stop processing fraud proofs for the same height h 
- Continue to consume and validate fraud proofs before h until fraud proof window is over
- IF fraud on h-k is valid 
    - update h to h-k

**Comment by Wondertan** [comment]
In the node we turn off services responsible for some functionality that has to halt via https://github.com/celestiaorg/celestia-node/blob/main/nodebuilder/fraud/lifecycle.go. If it turns out useful for you, we can upstream it in go-fraud.

**Comment by nashqueue** [comment]
This might be relevant https://github.com/rollkit/rollkit/pull/1000#discussion_r1239691053

**Comment by Manav-Aggarwal** [comment]
https://github.com/rollkit/rollkit/issues/1632#issuecomment-2408212822
