### ISSUE TITLE
Error occurred when calling the tendermint API from a rollup chain using rollkit.

### ISSUE THREAD

**Issue by kim201212** [rollkit/rollkit#944]
When I deploy the chain using `rollkit/cosmos-sdk`

Error as shown below: 
```
curl localhost:1317/cosmos/base/tendermint/v1beta1/syncing
{
  "code": 12,
  "message": "unknown service cosmos.base.tendermint.v1beta1.Service",
  "details": [
  ]
}
```

It seems looks like rollkit need to implement the `rollkit/cosmos-sdk` `rpc`.

**Comment by Manav-Aggarwal** [comment]
This should be handled in https://github.com/rollkit/rollkit/issues/1268
