### ISSUE TITLE
Error while running fraud service

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#945]
When nodes are started sequentially with peers configured, the fraud service expects the seed nodes to be already started, otherwise will result in the following error.

```2023-05-16T19:56:05.315-0500	ERROR	fraudserv	fraudserv/sync.go:74	error while requesting fraud proofs	{"err": "protocols not supported: [/state-fraud/fraud/v0.0.1]", "peer": "12D3KooWJXHwdV5dfhneCJYpkFRcoSZsVBK13Dzz2C1CsC2TyZMh"}```

**Comment by Manav-Aggarwal** [comment]
Not relevant anymore.
