### ISSUE TITLE
Fullnode after generating the fraud proof does not immediately force stop the node

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#947]
The fullnode after generating and broadcasting the fraud proof, exists the SyncLoop silently and upon receiving the gossiped fraud proof, cancels the context. This could lead to fullnode never stopping gracefully. This can be fixed partially by capturing the cancel event (which only happens upon receiving the fraud proof) and stopping the node gracefully. 

```
func (n *FullNode) OnStart() error {
  ...
  ...
  go func(ctx context.Context) {
		  select {
		  case <-ctx.Done():
			  n.Stop()
		  default:
		  }
  }(n.ctx)
  return nil
}
```

**Comment by Manav-Aggarwal** [comment]
Duplicate of https://github.com/rollkit/rollkit/issues/933
