### ISSUE TITLE
Require mod tidy after update of go version 

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#959]
After we get a new minor release for 1.19 : https://github.com/golang/go/issues/60351 and 
Or 1.20 https://github.com/golang/go/issues/60352

Orginial go issue:  https://github.com/golang/go/issues/60313

First Rollkit Issue that created the problem: https://github.com/rollkit/rollkit/pull/955

For us to get this fix we have to upgrade to go version 1.19 or 1.20 in the meantime. 

Depends on #960

**Comment by MSevey** [comment]
related, i disabled the test coverage from being required in the meantime as that calls go tidy as well.

**Comment by nashqueue** [comment]
we updated go and this is resolved resolved
