### ISSUE TITLE
Release workflow creates a minor bumb if you pick patch

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#961]
The release workflow creates a minor bump if you use the patch, it created a 0.8 instead of a 0.7.5 after being 7.4.

**Comment by MSevey** [comment]
is this still the case?

**Comment by nashqueue** [comment]
Not sure let's see with the new release cc @gupadhyaya

**Comment by Manav-Aggarwal** [comment]
@gupadhyaya

**Comment by gupadhyaya** [comment]
this issue was not reproducible as in the last release via workflow did the patch release correctly for v0.10.2
