### ISSUE TITLE
Move state witness subtree inclusion proofs from cosmos-sdk to rollkit

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#981]
Move the merkle inclusion proofs in the fraud proof that prove the witness data was part of the state machine’s appHash from cosmos-sdk to rollkit. Two PRs for respective repos.

https://github.com/rollkit/cosmos-sdk/blob/f6c90a66ed7d8006713ce0781ee0c770d5cc9b71/baseapp/fraudproof.go#L162

**Comment by Manav-Aggarwal** [comment]
https://github.com/rollkit/rollkit/issues/1632#issuecomment-2408212822
