### ISSUE TITLE
Handle multiple namespaces in mock server

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#993]
it is not possible to test different status messages for DALC using our mock server because it does not differentiate namespaces while creating the mock DALC: https://github.com/rollkit/rollkit/blob/main/da/celestia/mock/server.go#L47
This means, all namespace data gets stored into a single key-value store and querying for different namespaces would result in the same data.
We need to extend the mock server to create one mock DALC for each namespace.

**Comment by Manav-Aggarwal** [comment]
Related: #829

**Comment by Manav-Aggarwal** [comment]
Duplicate of https://github.com/rollkit/go-da/issues/94
